import { useCallback, useRef, useState } from 'react';
import { ArrowRight, CalendarDays, ChartNoAxesCombined, Check, CreditCard, Crown, FileText, Landmark, Mail, MessageCircle, MoreHorizontal, Plus, Receipt, RefreshCw, Search, Sparkles, Wallet } from 'lucide-react';
import { Badge, Card, Field, Modal, Toggle } from './kit';
import { friendlyError, safeExternalUrl, settingsApiEnabled, settingsRequest } from './data';
import type { SettingsData, Transaction } from './data';

const money = (amount: number) => `€${amount.toFixed(2)}`;
const serviceIcon = (name: string) => name === 'WhatsApp' ? MessageCircle : name === 'Email' ? Mail : name === 'AI Follow-Up' ? Sparkles : MoreHorizontal;
const serviceColor = (name: string) => name === 'WhatsApp' ? 'green' : name === 'Email' ? 'blue' : name === 'AI Follow-Up' ? 'purple' : 'neutral';
const billingTabs = [{ icon: CreditCard, name: 'Subscription' }, { icon: Wallet, name: 'Wallet' }, { icon: ChartNoAxesCombined, name: 'Usage' }, { icon: Receipt, name: 'Transactions' }];
export function BillingPanel({ data, refresh, saveLocal }: { data: SettingsData; refresh: () => Promise<void>; saveLocal: (data: SettingsData) => Promise<void> }) {
  const [tab, setTab] = useState('Wallet'), [amount, setAmount] = useState(50), [recharge, setRecharge] = useState(data.recharge), [dialog, setDialog] = useState<'credits' | 'method' | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [method, setMethod] = useState('card'), [query, setQuery] = useState(''), [type, setType] = useState('All');
  const rechargeRef = useRef<HTMLElement>(null), creditsRef = useRef<HTMLElement>(null);
  const idempotency = useRef<string | null>(null);
  const close = useCallback(() => { setDialog(null); setError(''); }, []);
  async function subscription() {
    setBusy(true); setError('');
    try { const result = await settingsRequest<{ url: string }>('/billing/portal', { returnUrl: window.location.href }); window.location.assign(safeExternalUrl(result.url)); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); }
  }
  const transactions = data.transactions.filter(t => (type === 'All' || t.type === type) && `${t.description} ${t.service} ${t.date}`.toLowerCase().includes(query.toLowerCase()));
  function table(full = false) {
    return <Card className="st-transactions" title={full ? 'Transactions' : 'Recent Transactions'} description="All wallet transactions, usage and top-ups." action={!full && <button className="st-link" onClick={() => setTab('Transactions')}>View All <ArrowRight size={14}/></button>}>
      {full && <div className="st-table-filters"><label className="st-search"><Search size={15}/><input aria-label="Search transactions" value={query} placeholder="Search transactions…" onChange={e => setQuery(e.target.value)}/></label><select aria-label="Transaction type" value={type} onChange={e => setType(e.target.value)}><option>All</option><option>Usage</option><option>Top Up</option></select></div>}
      <div className="st-table-scroll"><table><thead><tr>{['Date', 'Type', 'Description', 'Service', 'Amount', 'Balance'].map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{(full ? transactions : data.transactions.slice(0, 8)).map(t => <TransactionRow key={t.id} transaction={t}/>)}</tbody></table></div>{!(full ? transactions : data.transactions).length && <div className="st-empty"><Receipt size={25}/><p>No transactions to show.</p></div>}
    </Card>;
  }
  function usage() {
    return <Card title="Usage Overview" description="Your wallet usage across different services this month." action={<span className="st-date-range"><CalendarDays size={14}/>{data.usagePeriod}</span>}><div className="st-usage-grid">{data.usage.map(u => { const Icon = serviceIcon(u.service); return <div key={u.service} className="st-usage-service"><div className="st-usage-detail"><span className={`st-service-icon ${serviceColor(u.service)}`}><Icon size={19}/></span><div><small>{u.service}</small><b>{money(u.amount)}</b><p>{u.detail}</p></div></div><div className="st-progress-row"><div className="st-progress"><span className={serviceColor(u.service)} style={{ width: `${Math.max(0, Math.min(100, u.percentage))}%` }}/></div><small>{u.percentage}%</small></div></div>; })}</div></Card>;
  }
  return <>
    <div className="st-billing-title"><span className="st-heading-icon"><Wallet size={24}/></span><div><h2>Billing &amp; Wallet</h2><p>Manage your subscription, wallet balance and usage for AI, communication and other services.</p></div></div>
    <nav className="st-billing-tabs" aria-label="Billing navigation">{billingTabs.map(item => <button key={item.name} aria-current={tab === item.name ? 'page' : undefined} className={tab === item.name ? 'active' : ''} onClick={() => setTab(item.name)}><item.icon size={16}/>{item.name}</button>)}</nav>
    {!settingsApiEnabled && <p className="st-demo-note">Preview data · Connect the billing service to enable payments and see your live balance.</p>}
    {error && <p className="st-error" role="alert">{error}</p>}
    {(tab === 'Wallet' || tab === 'Subscription') && <div className="st-wallet-top"><Card className="st-balance-card"><span className="st-wallet-orb"><Wallet size={31}/></span><div><small>Wallet Balance</small><strong>{money(data.balance)}</strong><p>Available credits to use across all services.</p></div><div className="st-balance-actions"><button className="st-primary" onClick={() => { idempotency.current = crypto.randomUUID(); setDialog('credits'); }}><Plus size={15}/>Add Credits</button><div className="st-balance-recharge"><button className="st-link" onClick={() => rechargeRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' })}><RefreshCw size={13}/>Auto Recharge</button><Toggle label="Auto Recharge" checked={recharge.enabled} onChange={enabled => setRecharge({ ...recharge, enabled })}/></div></div></Card><Card className="st-plan-card"><span className="st-crown"><Crown size={23}/></span><div><small>Current Plan</small><h3>{data.plan.name} {data.plan.active && <Badge>Active</Badge>}</h3><b>{money(data.plan.price).replace('.00', '')} <span>/ month</span></b><p>Renews on {data.plan.renewal}</p></div><button className="st-secondary" disabled={busy} onClick={() => void subscription()}>Manage Subscription <ArrowRight size={14}/></button></Card></div>}
    {tab === 'Wallet' && <div className="st-wallet-grid"><div className="st-wallet-main">{usage()}{table()}</div><aside className="st-wallet-side">
      <section ref={creditsRef}><Card title="Add Credits" description="Top up your wallet to continue using all services."><div className="st-credit-amounts">{[10, 25, 50, 100].map(n => <button key={n} className={n === amount ? 'active' : ''} aria-pressed={n === amount} onClick={() => setAmount(n)}>€{n}</button>)}</div><button className="st-primary st-full" onClick={() => { idempotency.current = crypto.randomUUID(); setDialog('credits'); }}>Add €{amount} Credits <ArrowRight size={15}/></button></Card></section>
      <Card title="Payment Methods" description="Manage your payment methods for adding credits." action={<button className="st-secondary small" onClick={() => setDialog('method')}><Plus size={13}/>Add Payment Method</button>}><div className="st-payment-methods">{data.paymentMethods.map(m => <div className="st-payment-method" key={m.id}><span className={`st-payment-logo ${m.kind}`}>{m.kind === 'card' ? <b>VISA</b> : m.kind === 'paypal' ? <b>P</b> : <Landmark size={19}/>}</span><span><b>{m.name}</b><small>{m.detail}</small></span>{data.defaultMethod === m.id ? <Badge tone="purple">Default</Badge> : <button className="st-secondary small" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await settingsRequest('/billing/payment-methods/default', { id: m.id }); await refresh(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>Set as default</button>}</div>)}</div>{!data.paymentMethods.length && <p className="st-note">No payment methods added yet.</p>}</Card>
      <section ref={rechargeRef}><Card title="Auto Recharge" description="Automatically add credits when your balance is low." action={<Toggle label="Enable Auto Recharge" checked={recharge.enabled} onChange={enabled => setRecharge({ ...recharge, enabled })}/>}><div className="st-recharge-fields"><Field label="When balance is below"><select disabled={!recharge.enabled} value={recharge.below} onChange={e => setRecharge({ ...recharge, below: e.target.value })}>{[5, 10, 20, 50].map(n => <option key={n} value={n}>€{n}</option>)}</select></Field><Field label="Add this amount"><select disabled={!recharge.enabled} value={recharge.amount} onChange={e => setRecharge({ ...recharge, amount: e.target.value })}>{[10, 25, 50, 100].map(n => <option key={n} value={n}>€{n}</option>)}</select></Field><Field label="Payment method"><select disabled={!recharge.enabled} value={recharge.method} onChange={e => setRecharge({ ...recharge, method: e.target.value })}>{data.paymentMethods.filter(m => m.kind !== 'bank').map(m => <option key={m.id} value={m.id}>{m.name}{m.kind === 'card' ? ' •••• 4242' : ''}</option>)}</select></Field></div><button className="st-soft-button st-full" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { if (settingsApiEnabled) { await settingsRequest('/billing/recharge', recharge, 'PATCH'); await refresh(); } else { await saveLocal({ ...data, recharge }); } } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>{busy ? 'Saving…' : 'Save Settings'}</button></Card></section>
    </aside></div>}
    {tab === 'Transactions' && table(true)}
    {tab === 'Usage' && <>{usage()}<Card title="Usage details" description="Service charges recorded in your wallet ledger.">{table()}</Card></>}
    {tab === 'Subscription' && <Card title="Your subscription" description="Review your plan, renewal and billing preferences."><div className="st-subscription-detail"><Crown size={30}/><h3>{data.plan.name}</h3><p>{money(data.plan.price)} per month · Renews {data.plan.renewal}</p><ul><li><Check size={15}/>AI business tools and automation</li><li><Check size={15}/>CRM, inbox and booking workspace</li><li><Check size={15}/>Usage billed transparently through your wallet</li></ul><button className="st-primary" disabled={busy} onClick={() => void subscription()}>Manage Subscription <ArrowRight size={15}/></button></div></Card>}
    {dialog && <Modal title={dialog === 'credits' ? `Add €${amount} Credits` : 'Add Payment Method'} close={close}>
      <p>{dialog === 'credits' ? 'Complete payment securely with your provider. Credits appear after the payment is verified.' : 'Your payment provider securely stores your payment details. GOS does not store full card numbers.'}</p>
      {dialog === 'credits' ? <><div className="st-credit-amounts">{[10, 25, 50, 100].map(n => <button key={n} aria-pressed={n === amount} className={n === amount ? 'active' : ''} onClick={() => { setAmount(n); idempotency.current = crypto.randomUUID(); }}>€{n}</button>)}</div><Field label="Payment method"><select value={method} onChange={e => setMethod(e.target.value)}><option value="card">Credit Card</option><option value="paypal">PayPal</option><option value="bank">Bank Transfer</option></select></Field><div className="st-credit-summary"><span>Credits to add</span><b>€{amount}.00</b></div>{method === 'bank' && <p className="st-note">Bank transfers remain pending until confirmed. Your balance will update after approval.</p>}</> : <Field label="Payment method type"><select value={method} onChange={e => setMethod(e.target.value)}><option value="card">Credit Card</option><option value="paypal">PayPal</option><option value="bank">Bank Transfer</option></select></Field>}
      {error && <p className="st-error" role="alert">{error}</p>}<div className="st-modal-actions"><button className="st-secondary" onClick={close}>Cancel</button><button className="st-primary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { const result = await settingsRequest<{ url: string }>(dialog === 'credits' ? '/billing/checkout' : '/billing/payment-methods/setup', { ...(dialog === 'credits' ? { amount, currency: 'EUR', idempotencyKey: idempotency.current } : {}), method, returnUrl: `${window.location.origin}/dashboard/settings/billing` }); window.location.assign(safeExternalUrl(result.url)); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>{busy ? 'Opening checkout…' : 'Continue securely'}<ArrowRight size={15}/></button></div>
    </Modal>}
  </>;
}
function TransactionRow({ transaction: t }: { transaction: Transaction }) {
  const Icon = serviceIcon(t.service);
  return <tr><td>{t.date}</td><td><span className="st-transaction-type"><span className={`st-service-icon ${t.amount > 0 ? 'green' : 'purple'}`}>{t.amount > 0 ? <Plus size={13}/> : <FileText size={13}/>}</span>{t.type}</span></td><td>{t.description}</td><td><span className="st-transaction-service">{t.service !== '—' && <Icon size={13} className={serviceColor(t.service)}/>} {t.service}</span></td><td className={t.amount > 0 ? 'st-amount-positive' : 'st-amount-negative'}>{t.amount > 0 ? '+' : '-'}{money(Math.abs(t.amount))}</td><td>{money(t.balance)}</td></tr>;
}
