import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AlertCircle, ArrowRight, CalendarDays, CheckCircle2, ChevronRight, ExternalLink, Globe2, Mail, MessageCircle, Plug, Search, ShieldCheck, Sparkles, Unplug, Video, Webhook } from 'lucide-react';
import { useSelector } from 'react-redux';
import type { RootState } from '../../store';
import { InstagramIcon, FacebookIcon } from '../inbox/ChannelIcons';
import { Badge, Card, Field, Modal, Toggle } from './kit';
import { friendlyError, safeExternalUrl, settingsApiEnabled, settingsRequest } from './data';
import type { IntegrationState, SettingsData } from './data';
import { PanelHeading } from './kit';

const providers = [
  { id: 'meta', name: 'Facebook & Instagram', category: 'Communication', description: 'Manage Facebook and Instagram conversations in your unified inbox.', scopes: ['Read connected pages and business accounts', 'Receive and reply to customer messages'], icon: FacebookIcon, color: 'blue', status: 'https://metastatus.com/' },
  { id: 'whatsapp', name: 'WhatsApp Business', category: 'Communication', description: 'Connect WhatsApp for customer messaging and automated follow-ups.', scopes: ['Access your WhatsApp Business account', 'Send approved messages and receive replies'], icon: MessageCircle, color: 'green', status: 'https://metastatus.com/' },
  { id: 'gmail', name: 'Gmail', category: 'Communication', description: 'Send and receive customer emails from your connected Gmail account.', scopes: ['Read and send business emails', 'Identify the connected email account'], icon: Mail, color: 'red', status: 'https://www.google.com/appsstatus/dashboard/' },
  { id: 'outlook-email', name: 'Outlook Email', category: 'Communication', description: 'Bring Microsoft email conversations into your GOS inbox.', scopes: ['Read and send business emails', 'Identify your Microsoft account'], icon: Mail, color: 'blue', status: 'https://status.cloud.microsoft/' },
  { id: 'google-calendar', name: 'Google Calendar', category: 'Scheduling', description: 'Sync bookings, check availability and prevent double bookings.', scopes: ['Read calendar availability', 'Create and update booking events'], icon: CalendarDays, color: 'blue', status: 'https://www.google.com/appsstatus/dashboard/' },
  { id: 'outlook-calendar', name: 'Microsoft Calendar', category: 'Scheduling', description: 'Keep your Outlook calendar and GOS appointments in sync.', scopes: ['Read calendar availability', 'Create and update booking events'], icon: CalendarDays, color: 'blue', status: 'https://status.cloud.microsoft/' },
  { id: 'zoom', name: 'Zoom', category: 'Scheduling', description: 'Automatically create meeting links for your booked calls.', scopes: ['Create and manage scheduled meetings', 'Read your connected account profile'], icon: Video, color: 'blue', status: 'https://status.zoom.us/' },
  { id: 'stripe', name: 'Stripe', category: 'Payments', description: 'Accept payments for products, services and paid bookings.', scopes: ['Read connected account onboarding status', 'Create payments and access payout information'], icon: ShieldCheck, color: 'purple', status: 'https://status.stripe.com/' },
  { id: 'domains', name: 'Domains & DNS', category: 'Infrastructure', description: 'Connect your custom domain to published websites and funnels.', scopes: ['Verify domain ownership', 'Read DNS and SSL provisioning status'], icon: Globe2, color: 'orange', status: '' },
  { id: 'ai', name: 'AI Provider', category: 'Infrastructure', description: 'Configure the AI provider used by your workspace assistants.', scopes: ['Run approved AI requests', 'Read model availability and usage'], icon: Sparkles, color: 'purple', status: '' },
  { id: 'webhooks', name: 'Webhooks & API', category: 'Infrastructure', description: 'Connect your workflows using authenticated events and APIs.', scopes: ['Deliver selected workspace events', 'Access only the API scopes you approve'], icon: Webhook, color: 'purple', status: '' },
];
type Provider = typeof providers[number];
export function IntegrationsPanel({ data, refresh }: { data: SettingsData; refresh: () => Promise<void> }) {
  const [category, setCategory] = useState('All integrations'), [search, setSearch] = useState(''), [params, setParams] = useSearchParams();
  const [selected, setSelected] = useState<Provider | null>(providers.find(p => p.id === params.get('provider')) ?? null);
  const [logs, setLogs] = useState<string[] | null>(null), [logError, setLogError] = useState('');
  const role = useSelector((s: RootState) => s.auth.role);
  const close = useCallback(() => { setSelected(null); setParams(p => { p.delete('provider'); p.delete('connection'); return p; }, { replace: true }); }, [setParams]);
  const list = providers.filter(p => (category === 'All integrations' || p.category === category) && `${p.name} ${p.description}`.toLowerCase().includes(search.toLowerCase()));
  return <><PanelHeading title="Integrations" description="Connect your favorite tools and keep your business in sync."/>
    <div className="st-integration-toolbar"><div className="st-category-tabs" aria-label="Integration categories">{['All integrations', 'Communication', 'Scheduling', 'Payments', 'Infrastructure'].map(c => <button key={c} aria-pressed={category === c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><label className="st-search"><Search size={15}/><input aria-label="Search integrations" placeholder="Search integrations…" value={search} onChange={e => setSearch(e.target.value)}/></label></div>
    <div className="st-integration-grid">{list.map(p => { const state = data.integrations[p.id] ?? { status: 'Not Connected' }; return <Card key={p.id} className="st-integration-card"><div className="st-integration-top"><span className={`st-service-icon ${p.color}`}>{p.id === 'stripe' ? <b className="st-stripe-logo">stripe</b> : p.id === 'meta' ? <span className="st-meta-icons"><FacebookIcon size={21}/><InstagramIcon size={21}/></span> : <p.icon size={25}/>}</span><Badge tone={state.status === 'Connected' ? 'green' : state.status === 'Needs Attention' ? 'orange' : 'neutral'}>{state.status}</Badge></div><h3>{p.name}</h3><p>{p.description}</p>{state.status === 'Needs Attention' && <div className="st-integration-problem"><AlertCircle size={15}/><span>{state.problem || 'Your access needs to be renewed. Reconnect to resume syncing.'}</span></div>}<div className="st-integration-bottom"><small><i className={state.providerStatus === 'outage' ? 'outage' : ''}/>{state.providerStatus === 'outage' ? 'Provider disruption' : state.providerStatus === 'operational' ? 'Provider operational' : 'Status not checked'}</small><button className={state.status === 'Needs Attention' ? 'st-primary' : 'st-secondary'} onClick={() => setSelected(p)}>{state.status === 'Connected' ? 'Manage' : state.status === 'Needs Attention' ? 'Fix connection' : 'Connect'}<ChevronRight size={14}/></button></div></Card>; })}</div>
    {!list.length && <div className="st-empty"><Search size={30}/><h3>No integrations found</h3><p>Try a different search or category.</p><button className="st-secondary" onClick={() => { setSearch(''); setCategory('All integrations'); }}>Clear filters</button></div>}
    <div className="st-integration-note"><ShieldCheck size={18}/><p>You control what you connect. Disconnecting a tool preserves your historical workspace data.</p>{(role === 'ADMIN' || role === 'SUPER_ADMIN') && <button className="st-link" onClick={async () => { setLogs([]); setLogError(''); try { const result = await settingsRequest<{ entries: string[] }>('/integrations/logs'); setLogs(result.entries); } catch (e) { setLogError(friendlyError(e)); } }}>Admin logs <ArrowRight size={14}/></button>}</div>
    {selected && <ConnectionModal provider={selected} state={data.integrations[selected.id]} returned={params.get('connection') === 'return'} close={close} refresh={refresh}/>}
    {logs && <Modal title="Integration activity logs" close={() => setLogs(null)}>{logError ? <p className="st-error" role="alert">{logError}</p> : logs.length ? <ul className="st-log-list">{logs.map((l, i) => <li key={i}>{l}</li>)}</ul> : <p>No activity has been recorded.</p>}</Modal>}
  </>;
}
function ConnectionModal({ provider, state, returned, close, refresh }: { provider: Provider; state?: IntegrationState; returned: boolean; close: () => void; refresh: () => Promise<void> }) {
  const [step, setStep] = useState(state?.status === 'Connected' || returned ? 1 : 0), [connection, setConnection] = useState(state), [busy, setBusy] = useState(false), [error, setError] = useState(''), [tested, setTested] = useState(false), [sync, setSync] = useState(state?.sync ?? true), [disconnect, setDisconnect] = useState(false);
  const validate = useCallback(async () => {
    setBusy(true); setError('');
    try { const result = await settingsRequest<IntegrationState>(`/integrations/${provider.id}`); if (result.status !== 'Connected') throw new Error(result.problem || 'Authorization is not complete. Return to the provider and approve the requested access.'); setConnection(result); setStep(1); await refresh(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); }
  }, [provider.id, refresh]);
  useEffect(() => { if (returned) void validate(); }, [returned, validate]);
  async function authorize() {
    setBusy(true); setError('');
    try {
      const result = await settingsRequest<{ authorizeUrl: string }>(`/integrations/${provider.id}/authorize`, { returnUrl: `${window.location.origin}/dashboard/settings/integrations?provider=${provider.id}&connection=return` });
      window.location.assign(safeExternalUrl(result.authorizeUrl));
    } catch (e) { setError(friendlyError(e)); setBusy(false); }
  }
  return <Modal title={`Connect ${provider.name}`} close={close}><ol className="st-steps">{['Permissions', 'Validate connection', 'Preferences'].map((s, i) => <li className={i <= step ? 'active' : ''} key={s}><span>{i < step ? <CheckCircle2 size={14}/> : i + 1}</span>{s}</li>)}</ol>
    {step === 0 && <><div className="st-empty compact"><span className={`st-service-icon ${provider.color}`}><provider.icon size={29}/></span><h3>Bring {provider.name} into your workspace</h3><p>{provider.description}</p></div><h3>Permissions you’ll review</h3><ul className="st-scope-list">{provider.scopes.map(s => <li key={s}><ShieldCheck size={17}/>{s}</li>)}</ul><p className="st-note">You’ll authorize access securely with the provider, then return here for validation. You can disconnect at any time.</p><button className="st-primary st-full" disabled={busy} onClick={() => void authorize()}><ExternalLink size={16}/>{busy ? 'Opening provider…' : 'Connect / Authorize'}</button></>}
    {step === 1 && <><div className="st-connection-account"><CheckCircle2 size={25}/><div><b>{connection?.status === 'Connected' ? 'Connected account' : 'Validate your connection'}</b><p>{connection?.account || 'We’ll verify your authorization with the provider.'}</p></div>{connection?.status === 'Connected' && <Badge>Connected</Badge>}</div><p>Test your connection before enabling automatic syncing.</p>{tested && <p className="st-success" role="status"><CheckCircle2 size={17}/>Connection test passed.</p>}<div className="st-modal-actions"><button className="st-secondary" disabled={busy} onClick={async () => { setBusy(true); setTested(false); setError(''); try { const result = await settingsRequest<{ ok: boolean; problem?: string }>(`/integrations/${provider.id}/test`, {}); if (!result.ok) throw new Error(result.problem || 'The provider could not complete the test. Reauthorize access and try again.'); setTested(true); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}><Plug size={15}/>{busy ? 'Testing…' : 'Test Connection'}</button><button className="st-primary" disabled={connection?.status !== 'Connected' || busy} onClick={() => setStep(2)}>Continue <ArrowRight size={15}/></button></div><button className="st-link" disabled={busy} onClick={() => void validate()}>Validate authorization again</button></>}
    {step === 2 && <><h3>Connection preferences</h3><div className="st-preference"><span><b>Automatic sync</b><small>Keep your connected account and GOS up to date.</small></span><Toggle label="Automatic sync" checked={sync} onChange={setSync}/></div><Field label="Connected account"><input readOnly value={connection?.account ?? ''}/></Field><div className="st-modal-actions"><button className="st-danger" onClick={() => setDisconnect(true)} disabled={busy}><Unplug size={15}/>Disconnect</button><button className="st-primary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await settingsRequest(`/integrations/${provider.id}/settings`, { sync }, 'PATCH'); await refresh(); close(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>{busy ? 'Saving…' : 'Save connection'}</button></div></>}
    {disconnect && <div className="st-disconnect-confirm"><p>Disconnect {provider.name}? Syncing will stop. Your historical records will be kept.</p><div className="st-modal-actions"><button className="st-secondary" onClick={() => setDisconnect(false)}>Keep connected</button><button className="st-danger" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await settingsRequest(`/integrations/${provider.id}`, undefined, 'DELETE'); await refresh(); close(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>Confirm disconnect</button></div></div>}
    {error && <div className="st-error-box" role="alert"><AlertCircle size={18}/><div><b>Connection needs attention</b><p>{error}</p><button className="st-link" disabled={busy} onClick={() => { setError(''); setStep(0); }}>Fix: review connection setup <ArrowRight size={14}/></button>{provider.status && <a href={provider.status} target="_blank" rel="noreferrer">Check provider status <ExternalLink size={13}/></a>}</div></div>}
    {!settingsApiEnabled && <p className="st-note">Provider connections will be available once your workspace administrator connects the integration service.</p>}
  </Modal>;
}
