import { useCallback, useEffect, useState } from 'react';
import { Clock3, KeyRound, Mail, Monitor, Plus, ShieldCheck, UserRound, Users } from 'lucide-react';
import { useSelector } from 'react-redux';
import type { RootState } from '../../store';
import { Badge, Card, Field, Modal } from './kit';
import { friendlyError, settingsApiEnabled, settingsRequest } from './data';
import { PanelHeading } from './kit';
type Member = { id: string; name: string; email: string; role: string; active: boolean };
export function TeamPanel() {
  const user = useSelector((s: RootState) => s.auth.user), role = useSelector((s: RootState) => s.auth.role);
  const [members, setMembers] = useState<Member[]>([]), [email, setEmail] = useState(''), [inviteRole, setInviteRole] = useState('Member'), [open, setOpen] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [audit, setAudit] = useState<string[] | null>(null);
  const close = useCallback(() => setOpen(false), []);
  const canManage = role === 'ADMIN' || role === 'SUPER_ADMIN';
  const load = useCallback(async () => { if (!settingsApiEnabled) return; setBusy(true); try { const result = await settingsRequest<{ members: Member[] }>('/team'); setMembers(result.members); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function update(member: Member, change: Partial<Member>) { setBusy(true); setError(''); try { await settingsRequest(`/team/${member.id}`, change, 'PATCH'); await load(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  return <><PanelHeading title="Team & roles" description="Manage team members and permissions across your workspace."/><Card title="Team members" description="Invite your team and control their workspace access." action={<button className="st-primary" disabled={!canManage || busy} onClick={() => setOpen(true)}><Plus size={15}/>Invite member</button>}>
    {!canManage && <p className="st-note">Only workspace administrators can invite members or change roles.</p>}
    {!settingsApiEnabled && <p className="st-note">Connect the team service to see members and manage permissions.</p>}
    {error && <p className="st-error" role="alert">{error}</p>}
    {!members.length ? <div className="st-row"><span className="st-service-icon purple"><UserRound size={22}/></span><div><b>{user?.name ?? 'Current user'}</b><p>{user?.email ?? ''}</p></div><Badge>{role === 'USER' ? 'Member' : 'Admin'}</Badge></div> : <div className="st-table-scroll"><table><thead><tr><th>Member</th><th>Email</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{members.map(m => <tr key={m.id}><td>{m.name}</td><td>{m.email}</td><td><select aria-label={`Role for ${m.name}`} value={m.role} disabled={!canManage || busy || m.role === 'Owner'} onChange={e => void update(m, { role: e.target.value })}>{['Owner', 'Admin', 'Manager', 'Sales', 'Support', 'Member'].map(r => <option key={r}>{r}</option>)}</select></td><td><Badge tone={m.active ? 'green' : 'neutral'}>{m.active ? 'Active' : 'Inactive'}</Badge></td><td><button className="st-secondary small" disabled={!canManage || busy || m.role === 'Owner'} onClick={() => { if (window.confirm(`${m.active ? 'Deactivate' : 'Reactivate'} ${m.name}? Their workspace access will change.`)) void update(m, { active: !m.active }); }}>{m.active ? 'Deactivate' : 'Reactivate'}</button></td></tr>)}</tbody></table></div>}
  </Card><Card title="Permissions & audit" description="Role changes and sensitive actions are authorized and recorded by the workspace service."><div className="st-row"><Users size={25}/><p>Owners and admins manage access. Members work within the permissions assigned to their role.</p></div><button className="st-secondary" disabled={!canManage || busy} onClick={async () => { setBusy(true); setError(''); try { const result = await settingsRequest<{ entries: string[] }>('/team/audit'); setAudit(result.entries); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>View activity log</button></Card>{audit && <Modal title="Team activity" close={() => setAudit(null)}>{audit.length ? <ul>{audit.map((x, i) => <li key={i}>{x}</li>)}</ul> : <p>No recent activity.</p>}</Modal>}
    {open && <Modal title="Invite team member" close={close}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await settingsRequest('/team/invitations', { email, role: inviteRole }); await load(); close(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}><Field label="Email address"><input required type="email" value={email} onChange={e => setEmail(e.target.value)}/></Field><Field label="Role"><select value={inviteRole} onChange={e => setInviteRole(e.target.value)}>{['Admin', 'Manager', 'Sales', 'Support', 'Member'].map(r => <option key={r}>{r}</option>)}</select></Field>{error && <p className="st-error" role="alert">{error}</p>}<div className="st-modal-actions"><button type="button" className="st-secondary" onClick={close}>Cancel</button><button className="st-primary" disabled={busy}><Mail size={15}/>{busy ? 'Sending…' : 'Send invitation'}</button></div></form></Modal>}
  </>;
}
type Session = { id: string; device: string; lastActive: string; current: boolean };
export function SecurityPanel() {
  const [password, setPassword] = useState(''), [nextPassword, setNextPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [sessions, setSessions] = useState<Session[]>([]), [history, setHistory] = useState<string[]>([]), [mfa, setMfa] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { if (settingsApiEnabled) settingsRequest<{ sessions: Session[]; history: string[]; mfa: boolean }>('/security').then(r => { setSessions(r.sessions); setHistory(r.history); setMfa(r.mfa); }).catch(e => setError(friendlyError(e))); }, []);
  async function action(path: string, body?: unknown) {
    setBusy(true); setError(''); setMessage('');
    try { const result = await settingsRequest<{ url?: string; message?: string }>(path, body ?? {}); if (result?.url) { const url = new URL(result.url); if (url.protocol !== 'https:') throw new Error('The security service returned an invalid link.'); window.location.assign(url.href); } else setMessage(result?.message ?? 'Security settings updated.'); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); }
  }
  return <><PanelHeading title="Security" description="Protect your account and manage trusted access."/>{error && <p className="st-error" role="alert">{error}</p>}{message && <p className="st-success" role="status">{message}</p>}
    <form onSubmit={async e => { e.preventDefault(); if (nextPassword !== confirmation) { setError('The new passwords do not match.'); return; } await action('/security/password', { currentPassword: password, newPassword: nextPassword }); setPassword(''); setNextPassword(''); setConfirmation(''); }}><Card title="Password" description="Use a strong, unique password for your account."><div className="st-form-grid"><Field label="Current password"><input required type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)}/></Field><Field label="New password"><input required type="password" autoComplete="new-password" minLength={12} value={nextPassword} onChange={e => setNextPassword(e.target.value)}/></Field><Field label="Confirm new password"><input required type="password" autoComplete="new-password" value={confirmation} onChange={e => setConfirmation(e.target.value)}/></Field></div><p className="st-note">Use at least 12 characters.</p><button className="st-primary" disabled={busy}><KeyRound size={15}/>{busy ? 'Updating…' : 'Update Password'}</button></Card></form>
    <Card title="Two-factor authentication" description="Add another layer of protection when you sign in."><div className="st-row"><span className="st-service-icon purple"><ShieldCheck size={24}/></span><div><b>{mfa ? 'Enabled' : 'Not enabled'}</b><p>Use an authenticator app to secure your account.</p></div><button className="st-secondary" disabled={busy} onClick={() => void action('/security/mfa/setup')}>{mfa ? 'Manage 2FA' : 'Set up 2FA'}</button></div></Card>
    <Card title="Active sessions" description="Review the devices signed in to your account.">{sessions.length ? sessions.map(s => <div className="st-row" key={s.id}><Monitor size={22}/><div><b>{s.device}</b><p>{s.lastActive}</p></div>{s.current ? <Badge>Current</Badge> : <button disabled={busy} className="st-danger" onClick={async () => { if (!window.confirm('Sign out this device?')) return; setBusy(true); try { await settingsRequest(`/security/sessions/${s.id}`, undefined, 'DELETE'); setSessions(p => p.filter(x => x.id !== s.id)); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }}>Revoke</button>}</div>) : <p className="st-note">{settingsApiEnabled ? 'No other sessions found.' : 'Connect the account service to review active sessions.'}</p>}</Card>
    <Card title="Login history" description="Recent sign-in activity for your account.">{history.length ? history.map((h, i) => <div className="st-row" key={i}><Clock3 size={17}/><span>{h}</span></div>) : <p className="st-note">No login history available.</p>}</Card>
    <Card title="API access" description="Manage API keys and scoped permissions in your secure workspace portal."><button className="st-secondary" disabled={busy} onClick={() => void action('/security/api-keys/portal')}>Manage API Keys</button></Card>
  </>;
}
