import { useId, useState } from 'react';
import { Link, useLocation, useParams, useSearchParams } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { ArrowLeft, ArrowRight, CalendarDays, CheckSquare, Clock3, Mail, MessageCircle, Phone, Plus, Sparkles, Users, LayoutDashboard, Activity, MessageSquare, Calendar, Briefcase, Package, MoreHorizontal } from 'lucide-react';
import type { AppDispatch, RootState } from '../../store';
import { addLeadNote, moveLead, setLeadConsent, setLeadFollowUpState, updateLead, FOLLOW_UP_LIFECYCLE, type CanonicalLead, type FollowUpLifecycleState } from '../../store/slices/crmSlice';
import { bookings, products } from '../../data/mockData';
import { CRMAvatar, SourceBadge } from '../CRMLeads';
import { CustomSelect, CustomDatePicker } from './CRMPrimitives';
import { displayStage, euro, owners } from './model';
import { showToast } from '../../utils/toast';
import '../crm-leads.css';
import './crm-workspace.css';

const recordTabs = [
  { id: 'Overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'Activity Timeline', label: 'Activity timeline', icon: Activity },
  { id: 'Conversation History', label: 'Conversation history', icon: MessageSquare },
  { id: 'Appointments', label: 'Appointments', icon: Calendar },
  { id: 'Deals/Opportunities', label: 'Deals/Opportunities', icon: Briefcase },
  { id: 'Products/Orders', label: 'Products & Orders', icon: Package },
  { id: 'Notes/Tasks', label: 'Notes & Tasks', icon: CheckSquare },
  { id: 'AI Automation Status', label: 'AI Automation', icon: Sparkles }
];

/** WhatsApp outline glyph (speech bubble + handset), stroke-based to match Lucide weight. */
function WhatsAppIcon({ size = 18 }: { size?: number }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 21l1.65-3.8a9 9 0 1 1 3.4 2.9L3 21"/><path d="M9 10a.5.5 0 0 0 1 0V9a.5.5 0 0 0-1 0v1a5 5 0 0 0 5 5h1a.5.5 0 0 0 0-1h-1a.5.5 0 0 0 0 1"/></svg>;
}

/** Instagram outline glyph with the official brand gradient stroke. */
function InstagramIcon({ size = 18 }: { size?: number }) {
  const gid = `ig-grad-${useId().replace(/:/g, '')}`;
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={`url(#${gid})`} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><defs><linearGradient id={gid} gradientUnits="userSpaceOnUse" x1="4" y1="20" x2="20" y2="4"><stop offset="0" stopColor="#FEDA75"/><stop offset=".25" stopColor="#FA7E1E"/><stop offset=".5" stopColor="#E1306C"/><stop offset=".75" stopColor="#C13584"/><stop offset="1" stopColor="#833AB4"/></linearGradient></defs><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></svg>;
}

const tileClass = 'w-16 h-16 flex flex-col items-center justify-center gap-1 rounded-xl border border-slate-100 bg-white shadow-sm hover:shadow hover:-translate-y-px transition-all cursor-pointer aria-disabled:opacity-50 aria-disabled:pointer-events-none';
const tileLabel = 'text-[11px] font-medium leading-none text-slate-600';

export function CRMRecord() {
  const { id } = useParams(); const location = useLocation(); const dispatch = useDispatch<AppDispatch>(); const [params, setParams] = useSearchParams();
  const { leads, pipelines } = useSelector((s: RootState) => s.crm); const lead = leads.find(l => l.id === id);
  const [note, setNote] = useState(''); const [tag, setTag] = useState(''); const [taskTitle, setTaskTitle] = useState(''); const [due, setDue] = useState('');
  const base = location.pathname.startsWith('/dashboard') ? '/dashboard/crm' : '/crm';
  const tab = recordTabs.some(t => t.id === params.get('tab')) ? params.get('tab')! : 'Overview';
  if (!lead) return <div className="crm2-page crm-workspace"><div className="crm-empty"><Users size={36}/><h1>Contact not found</h1><p>This contact may have been deleted.</p><Link className="crm2-btn-primary" to={`${base}/contacts`}>Back to contacts</Link></div></div>;
  const pipeline = pipelines.find(p => p.id === (lead.pipelineId ?? 'main')) ?? pipelines[0];
  const stage = pipeline.stages.find(s => s.id === displayStage(lead, pipeline))!;
  const contactBookings = bookings.filter(b => b.leadId === lead.id);
  function save(changes: Partial<CanonicalLead>) { dispatch(updateLead({ id: lead!.id, changes })); showToast.success('Contact updated.'); }
  function field(key: 'name' | 'email' | 'phone' | 'company' | 'interest', label: string, type = 'text') {
    return <label className="crm-field">{label}<input key={`${lead!.id}-${key}-${lead![key]}`} aria-label={label} type={type} defaultValue={lead![key] ?? ''} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur(); }} onBlur={e => { const value = e.currentTarget.value.trim(); if (value === (lead![key] ?? '')) return; if ((key === 'name' && !value) || (key === 'email' && (!e.currentTarget.checkValidity() || !value || leads.some(l => l.id !== lead!.id && l.email.toLowerCase() === value.toLowerCase())))) { showToast.error('Enter a valid, unique contact value.'); e.currentTarget.value = lead![key] ?? ''; return; } save({ [key]: value, ...(key === 'name' ? { avatar: value.split(/\s+/).slice(0, 2).map(n => n[0]).join('').toUpperCase() } : {}) }); }}/></label>;
  }
  const timeline = (type?: string) => {
    const items = lead.activities.filter(a => !type || a.type === type);
    return items.length ? items.map(a => <div className="crm-feed-item" key={a.id}><span className="crm-feed-icon"><Clock3 size={16}/></span><div><b>{a.title}</b><p>{a.detail}</p></div><small>{a.at.includes('T') ? new Date(a.at).toLocaleString() : a.at}</small></div>) : [<div key="empty" className="crm-empty"><MessageCircle size={30}/><h3>No {type === 'message' ? 'conversations' : 'activities'} recorded yet</h3></div>];
  };
  return <div className="crm2-page crm-workspace crm-record"><div className="crm-record-breadcrumb"><Link to={`${base}/pipeline?pipeline=${pipeline.id}`}><ArrowLeft size={14}/>Back to pipeline</Link><span>/</span><Link to={`${base}/contacts?pipeline=${pipeline.id}`}>Contacts</Link><span>/</span><b>{lead.name}</b></div><header className="crm-record-header"><CRMAvatar lead={lead}/><div><h1>{lead.name}<span className="crm-stage-pill" style={{ color: stage.color }}>{lead.archived ? 'Archived' : stage.label}</span></h1><p>{lead.company || 'Independent contact'} · Assigned to {lead.owner}</p></div><div className="ml-auto flex flex-wrap items-center gap-2 max-[1100px]:ml-0">
    <a id="crm-record-action-call" aria-disabled={!lead.phone} className={tileClass} href={lead.phone ? `tel:${lead.phone.replace(/[^+\d]/g, '')}` : undefined} title="Call"><span className="text-emerald-500 bg-emerald-50/50 p-2 rounded-lg"><Phone size={18} strokeWidth={2}/></span><span className={tileLabel}>Call</span></a>
    <a id="crm-record-action-whatsapp" aria-disabled={!lead.phone} className={tileClass} href={lead.phone ? `https://wa.me/${lead.phone.replace(/\D/g, '')}` : undefined} target="_blank" rel="noreferrer" title="WhatsApp"><span className="text-[#25D366] bg-green-50/50 p-2 rounded-lg"><WhatsAppIcon/></span><span className={tileLabel}>WhatsApp</span></a>
    <a id="crm-record-action-email" className={tileClass} href={`mailto:${lead.email}`} title="Email"><span className="text-purple-600 bg-purple-50/50 p-2 rounded-lg"><Mail size={18} strokeWidth={2}/></span><span className={tileLabel}>Email</span></a>
    <Link id="crm-record-action-instagram" className={tileClass} to={`/dashboard/inbox?leadId=${encodeURIComponent(lead.id)}&channel=instagram`} title="Instagram"><span className="text-[#E1306C] bg-pink-50/50 p-2 rounded-lg"><InstagramIcon/></span><span className={tileLabel}>Instagram</span></Link>
    <button id="crm-record-action-archive" type="button" className={tileClass} onClick={() => save({ archived: !lead.archived })} title={lead.archived ? 'Restore contact' : 'Archive contact'}><span className="text-slate-400 bg-slate-50 p-2 rounded-lg"><MoreHorizontal size={18}/></span><span className={tileLabel}>{lead.archived ? 'Restore' : 'Archive'}</span></button>
  </div></header><nav className="flex-none bg-white px-5 border-b border-slate-200" aria-label="Contact record tabs"><div className="-mb-px flex gap-6 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{recordTabs.map(t => { const active = tab === t.id; return <button key={t.id} id={`crm-record-tab-${t.id.toLowerCase().replace(/[^a-z]+/g, '-')}`} type="button" className={`inline-flex items-center gap-1.5 whitespace-nowrap bg-transparent pt-3 pb-2.5 text-[13px] border-b-2 transition-colors duration-150 cursor-pointer ${active ? 'text-purple-600 font-semibold border-purple-600' : 'text-slate-500 font-medium border-transparent hover:text-slate-800 hover:border-slate-300'}`} aria-current={active ? 'page' : undefined} onClick={() => setParams({ tab: t.id })}><t.icon size={16} className={active ? 'text-purple-600' : 'text-slate-400'}/>{t.label}</button>; })}</div></nav><div className="crm-scroll-content">
    {tab === 'Overview' && <div className="crm-record-grid"><section className="crm-record-panel"><h2>Contact information</h2><p className="crm-muted">Edit a field and leave it to save.</p><div className="crm-form-grid">{field('name', 'Name')}{field('email', 'Email', 'email')}{field('phone', 'Phone', 'tel')}{field('company', 'Company')}<label className="crm-field">Owner<CustomSelect aria-label="Assigned owner" value={lead.owner} onChange={val => save({ owner: val })} options={[...new Set([...owners, ...leads.map(l => l.owner)])].map(o => ({ value: o, label: o }))} /></label><label className="crm-field">Source<CustomSelect aria-label="Contact source" value={lead.source} onChange={val => save({ source: val })} options={[...new Set(['Website', 'Instagram', 'WhatsApp', 'Referral', 'LinkedIn', lead.source])].map(s => ({ value: s, label: s }))} /></label>{field('interest', 'Interest')}</div><h3>Tags</h3><div className="crm-record-tags">{lead.tags.map(t => <button key={t} aria-label={`Remove tag ${t}`} onClick={() => save({ tags: lead.tags.filter(v => v !== t) })}>{t} ×</button>)}</div><form className="crm-inline-form" onSubmit={e => { e.preventDefault(); if (tag.trim()) { save({ tags: [...new Set([...lead.tags, tag.trim()])] }); setTag(''); } }}><input aria-label="New tag" placeholder="Add a tag" value={tag} onChange={e => setTag(e.target.value)}/><button className="crm2-btn-secondary" disabled={!tag.trim()}><Plus size={14}/>Add</button></form></section><section className="crm-record-panel"><h2>Relationship summary</h2><div className="crm-record-summary"><SourceBadge source={lead.source}/><b>{euro(lead.value)}</b><span>Opportunity value</span></div><label className="crm-field">Pipeline<CustomSelect aria-label="Contact pipeline" value={pipeline.id} onChange={val => { const next = pipelines.find(p => p.id === val)!; save({ pipelineId: next.id, stage: next.stages[0].id, lifecycleStage: next.stages[0].id }); }} options={pipelines.map(p => ({ value: p.id, label: p.name }))} /></label><label className="crm-field">Pipeline stage<CustomSelect aria-label="Contact pipeline stage" value={stage.id} onChange={val => dispatch(moveLead({ id: lead.id, stage: pipeline.stages.find(s => s.id === val)!.id }))} options={pipeline.stages.map(s => ({ value: s.id, label: s.label }))} /></label><label className="crm-field">Qualification<CustomSelect value={lead.qualificationStatus} onChange={val => save({ qualificationStatus: val as CanonicalLead['qualificationStatus'] })} options={['Pending', 'Qualified', 'Unqualified'].map(s => ({ value: s, label: s }))} /></label><label className="crm-field">Next follow-up<CustomDatePicker type="datetime-local" aria-label="Next follow-up" value={lead.nextFollowUpAt ?? ''} onChange={val => save({ nextFollowUpAt: val, nextFollowUp: val ? new Date(val).toLocaleString() : undefined })} /></label>{lead.nextFollowUp && <p className="crm-muted">Scheduled: {lead.nextFollowUp}</p>}<h3>Recent activity</h3>{timeline().slice(0, 3)}</section></div>}
    {tab === 'Activity Timeline' && <section className="crm-record-panel"><h2>Activity timeline</h2>{timeline()}</section>}
    {tab === 'Conversation History' && <section className="crm-record-panel"><div className="crm-section-heading"><h2>Conversation history</h2><Link className="crm2-btn-primary" to={`/dashboard/inbox?leadId=${lead.id}`}><MessageCircle size={14}/>Open inbox</Link></div>{timeline('message')}</section>}
    {tab === 'Appointments' && <section className="crm-record-panel"><div className="crm-section-heading"><h2>Appointments</h2><Link className="crm2-btn-primary" to="/dashboard/booking"><CalendarDays size={14}/>Manage bookings</Link></div><label className="crm-field">Booking status<CustomSelect value={lead.bookingStatus} onChange={val => save({ bookingStatus: val as CanonicalLead['bookingStatus'] })} options={['Not Scheduled', 'Offer Sent', 'Booked', 'Completed'].map(s => ({ value: s, label: s }))} /></label>{contactBookings.map(b => <div className="crm-feed-item" key={b.id}><CalendarDays size={20}/><div><b>{products.find(p => p.id === b.productId)?.name ?? 'Appointment'}</b><p>{b.date} · {b.time}</p></div><span className="crm-stage-pill">{b.status}</span></div>)}{!contactBookings.length && <div className="crm-empty"><CalendarDays size={30}/><h3>No appointments linked</h3><p>Use Booking &amp; Calendar to manage appointments.</p></div>}</section>}
    {tab === 'Deals/Opportunities' && <section className="crm-record-panel"><div className="crm-section-heading"><div><h2>{lead.interest || `${lead.name}'s opportunity`}</h2><p>{pipeline.name}</p></div><b className="crm-deal-value">{euro(lead.value)}</b></div><div className="crm-form-grid"><label>Deal value (€)<input aria-label="Deal value" type="number" min="0" step="0.01" defaultValue={lead.value} onBlur={e => { const value = Number(e.target.value); if (Number.isFinite(value) && value >= 0 && e.target.value !== '') save({ value }); else e.target.value = String(lead.value); }}/></label><label>Stage<CustomSelect aria-label="Opportunity stage" value={stage.id} onChange={val => dispatch(moveLead({ id: lead.id, stage: pipeline.stages.find(s => s.id === val)!.id }))} options={pipeline.stages.map(s => ({ value: s.id, label: s.label }))} /></label>{field('interest', 'Opportunity name')}</div><div className="crm-deal-stages">{pipeline.stages.map(s => <button key={s.id} className={s.id === stage.id ? 'active' : ''} onClick={() => dispatch(moveLead({ id: lead.id, stage: s.id }))}><i style={{ background: s.color }}/>{s.label}<ArrowRight size={12}/></button>)}</div>{timeline('stage')}</section>}
    {tab === 'Products/Orders' && <section className="crm-record-panel"><div className="crm-section-heading"><h2>Products &amp; orders</h2><Link className="crm2-btn-secondary" to="/dashboard/products">Manage products <ArrowRight size={14}/></Link></div>{lead.activities.some(a => a.type === 'payment') ? timeline('payment') : <div className="crm-empty"><h3>No orders recorded for this contact</h3><p>Recorded payments will appear here.</p></div>}{contactBookings.map(b => { const product = products.find(p => p.id === b.productId); return product && <div className="crm-feed-item" key={b.id}><div><b>{product.name}</b><p>Linked through appointment · {product.type}</p></div><span>{product.currency} {product.price.toLocaleString()}</span></div>; })}</section>}
    {tab === 'Notes/Tasks' && <div className="crm-record-grid"><section className="crm-record-panel"><h2>Internal notes</h2><form onSubmit={e => { e.preventDefault(); if (!note.trim()) return; dispatch(addLeadNote({ id: lead.id, note: note.trim() })); setNote(''); showToast.success('Note saved.'); }}><textarea aria-label="New note" className="crm-note-input" rows={4} placeholder="Add context for your team…" value={note} onChange={e => setNote(e.target.value)}/><button className="crm2-btn-primary" disabled={!note.trim()}><Plus size={14}/>Save note</button></form>{lead.notes.map((n, i) => <div className="crm-note" key={`${i}-${n}`}>{n}</div>)}</section><section className="crm-record-panel"><h2>Contact tasks</h2><form className="crm-contact-task-form" onSubmit={e => { e.preventDefault(); save({ tasks: [...(lead.tasks ?? []), { id: crypto.randomUUID(), title: taskTitle.trim(), due, done: false }] }); setTaskTitle(''); }}><input aria-label="Contact task title" placeholder="Task title" value={taskTitle} onChange={e => setTaskTitle(e.target.value)} required/><CustomDatePicker aria-label="Contact task due date" value={due} onChange={val => setDue(val)} placeholder="Due date" /><button className="crm2-btn-primary" disabled={!taskTitle.trim() || !due}><CheckSquare size={14}/>Add task</button></form>{(lead.tasks ?? []).map(t => <div className="crm-task-row" key={t.id}><input type="checkbox" aria-label={`Complete ${t.title}`} checked={t.done} onChange={() => save({ tasks: lead.tasks!.map(task => task.id === t.id ? { ...task, done: !task.done } : task) })}/><span className={t.done ? 'crm-task-done' : ''}>{t.title}</span><small>{t.due}</small><button className="crm-danger" onClick={() => save({ tasks: lead.tasks!.filter(task => task.id !== t.id) })}>Remove</button></div>)}</section></div>}
    {tab === 'AI Automation Status' && <section className="crm-record-panel"><div className="crm-section-heading"><div><h2><Sparkles size={18}/>AI automation status</h2><p>Control this contact’s consent and follow-up lifecycle.</p></div><Link className="crm2-btn-primary" to={`/dashboard/follow-up?leadId=${lead.id}`}>Open AI Follow-Up <ArrowRight size={14}/></Link></div><label className="crm-field">Follow-up lifecycle<CustomSelect aria-label="Follow-up lifecycle" value={lead.followUpState} onChange={val => dispatch(setLeadFollowUpState({ id: lead.id, followUpState: val as FollowUpLifecycleState }))} options={FOLLOW_UP_LIFECYCLE.map(s => ({ value: s.state, label: s.label }))} /></label><p className="crm-muted">{FOLLOW_UP_LIFECYCLE.find(s => s.state === lead.followUpState)?.description}</p><div className="crm-consents">{(['hasWhatsAppConsent', 'hasMessagingConsent', 'hasEmailConsent'] as const).map((key, i) => <label key={key}><input type="checkbox" checked={lead[key]} onChange={e => dispatch(setLeadConsent({ id: lead.id, consent: { [key]: e.target.checked } }))}/>{['WhatsApp consent', 'Social messaging consent', 'Email consent'][i]}</label>)}</div><p className="crm-muted">Lifecycle and consent preferences are saved to this workspace. Channel delivery uses the integrations configured in GOS.</p></section>}
  </div></div>;
}


