import { useState } from 'react';
import { ArrowDown, ArrowUp, Copy, GripVertical, Settings, Trash2 } from 'lucide-react';
import { SectionPreview } from './BuilderWorkspace';
import type { BuilderPage, BuilderSection } from './BuilderWorkspace';
import type { DropTarget } from './funnel-tree';
type Props={page:BuilderPage;selected:string|null;device:string;select:(id:string)=>void;drop:(event:React.DragEvent,target:DropTarget)=>void;duplicate:(id:string)=>void;remove:(id:string)=>void;move:(id:string,target:DropTarget)=>void;content:(id:string,key:string,value:string)=>void;settings:(id:string)=>void};
export function FunnelCanvas({page,selected,device,select,drop,duplicate,remove,move,content,settings}:Props){
 const [active,setActive]=useState(''),[moving,setMoving]=useState(false);
 const accepts=(event:React.DragEvent)=>['text/gos-block','text/gos-section'].some(type=>event.dataTransfer.types.includes(type));
 const zone=(target:DropTarget,key:string,empty=false)=><div key={'zone-'+key} className={'fn-drop-zone '+(active===key?'active ':'')+(empty?'empty':'')} data-drop-before={target.beforeId??'end'} data-drop-parent={target.parentId??'root'} data-drop-column={target.column??''} aria-label={empty?'Drop an element into this column':'Insert an element here'} onDragOver={event=>{if(!accepts(event))return;event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect=event.dataTransfer.types.includes('text/gos-section')?'move':'copy';setActive(key);setMoving(true);}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setActive('');}} onDrop={event=>{if(!accepts(event))return;event.preventDefault();event.stopPropagation();drop(event,target);setActive('');setMoving(false);}}><span>{empty?'Drop element here':'Insert here'}</span></div>;
 const render=(items:BuilderSection[],parentId?:string,column?:number):React.ReactNode=>items.map((item,index)=>{
 const target={parentId,column,beforeId:item.id},isSelected=selected===item.id;
 const visibility=item.styles.visibility,hidden=visibility==='Hidden'||visibility==='Desktop only'&&device!=='desktop'||visibility==='Tablet only'&&device!=='tablet'||visibility==='Mobile only'&&device!=='mobile';
 return <div key={item.id} className="fn-canvas-node">{zone(target,item.id)}<section tabIndex={0} aria-label={item.type+' element'} data-section-id={item.id} data-element-type={item.type} className={'fb-canvas-section fn-editable-section '+(item.type==='Hero'?'fb-hero-section ':'')+(isSelected?'selected':'')} style={{backgroundColor:item.styles.backgroundColor,padding:item.styles.padding+'px 22px',textAlign:item.styles.textAlign.toLowerCase() as React.CSSProperties['textAlign'],fontFamily:item.styles.typography==='Brand heading'?'var(--fb-heading-font)':undefined,minHeight:item.content.sectionHeight==='Screen Height'?'100vh':undefined,maxWidth:item.content.contentWidth==='Boxed'?'1100px':undefined,marginInline:item.content.contentWidth==='Boxed'?'auto':undefined,backgroundImage:item.type!=='Image'&&item.content.src?'url('+item.content.src+')':undefined,backgroundSize:'cover',display:hidden?'none':undefined}} onClick={event=>{event.stopPropagation();select(item.id);}} onFocus={event=>{if(event.target===event.currentTarget)select(item.id);}} onDragOver={event=>{if(!accepts(event))return;event.preventDefault();event.stopPropagation();setMoving(true);const rect=event.currentTarget.getBoundingClientRect();setActive(event.clientY<rect.top+rect.height/2?item.id:items[index+1]?.id??(parentId?parentId+'-col-'+column:'root-end'));const frame=event.currentTarget.closest<HTMLElement>('.fb-site-frame');if(frame){const bounds=frame.getBoundingClientRect();if(event.clientY<bounds.top+45)frame.scrollTop-=12;else if(event.clientY>bounds.bottom-45)frame.scrollTop+=12;}}} onDrop={event=>{if(!accepts(event))return;event.preventDefault();event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();drop(event,event.clientY<rect.top+rect.height/2?target:{parentId,column,beforeId:items[index+1]?.id});setActive('');setMoving(false);}}>
 <div className="fn-element-actions" aria-label={item.type+' quick actions'} onClick={event=>event.stopPropagation()}>
 <button draggable aria-label={'Move '+item.type+' element'} title="Drag to move" onDragStart={event=>{event.stopPropagation();event.dataTransfer.setData('text/gos-section',item.id);event.dataTransfer.effectAllowed='move';setMoving(true);}} onDragEnd={()=>{setMoving(false);setActive('');}}><GripVertical size={13}/><span>{item.type}</span></button>
 <button aria-label={'Move '+item.type+' up'} disabled={!index} onClick={()=>move(item.id,{parentId,column,beforeId:items[index-1]?.id})}><ArrowUp size={12}/></button><button aria-label={'Move '+item.type+' down'} disabled={index===items.length-1} onClick={()=>move(item.id,{parentId,column,beforeId:items[index+2]?.id})}><ArrowDown size={12}/></button>
 <button aria-label={'Duplicate '+item.type} onClick={()=>duplicate(item.id)}><Copy size={13}/></button><button aria-label={'Settings for '+item.type} onClick={()=>settings(item.id)}><Settings size={13}/></button><button aria-label={'Delete '+item.type} onClick={()=>remove(item.id)}><Trash2 size={13}/></button></div>
 {item.type==='Columns'?<><div className="fn-column-layout" style={{gridTemplateColumns:item.content.columnLayout?.includes('30/70')?'3fr 7fr':'repeat('+(item.content.columnLayout?.startsWith('3')?3:item.content.columnLayout?.startsWith('1')?1:2)+',minmax(0,1fr))',gap:item.content.gap+'px'}}>{Array.from({length:item.content.columnLayout?.startsWith('3')?3:item.content.columnLayout?.startsWith('1')?1:2},(_,col)=><div className="fn-column" key={col} aria-label={'Column '+(col+1)}>{render(item.children?.[col]??[],item.id,col)}{zone({parentId:item.id,column:col},item.id+'-col-'+col,!(item.children?.[col]?.length))}</div>)}</div></>
 :item.type==='Hero'?<><img className="fb-hero-image" src={page.featuredImage} alt=""/><span className="fb-hero-overlay"/><div className="fb-hero-copy"><small>HERO SECTION</small><h1 contentEditable suppressContentEditableWarning aria-label="Inline heading" onBlur={event=>content(item.id,'title',event.currentTarget.textContent??'')}>{item.content.title}</h1><p contentEditable suppressContentEditableWarning aria-label="Inline paragraph" onBlur={event=>content(item.id,'body',event.currentTarget.textContent??'')}>{item.content.body}</p>{item.content.button&&<button className="fb-site-primary" onClick={()=>select(item.id)}>{item.content.button}</button>}</div></>
 :['Heading','Text','Paragraph'].includes(item.type)?<div className="fn-inline-copy">{item.type==='Heading'||item.content.headingTag?.startsWith('H')?<h2 contentEditable suppressContentEditableWarning aria-label="Inline heading" onBlur={event=>content(item.id,'title',event.currentTarget.textContent??'')}>{item.content.title||'Write your heading'}</h2>:null}<p contentEditable suppressContentEditableWarning aria-label="Inline paragraph" onBlur={event=>content(item.id,'body',event.currentTarget.textContent??'')}>{item.content.body||'Write your text'}</p></div>
 :<SectionPreview item={item} onAction={()=>select(item.id)} onImagePick={()=>settings(item.id)} onImageDrop={event=>{event.preventDefault();event.stopPropagation();}} onNotify={()=>{}}/>}
 {item.styles.customCss&&<style>{'[data-section-id="'+item.id+'"]{'+item.styles.customCss+'}'}</style>}
 </section></div>;
 });
 return <div className={'fn-focused-canvas '+(moving?'dragging':'')} data-page-id={page.id} onDragEnd={()=>{setMoving(false);setActive('');}}>{render(page.sections)}{zone({},'root-end',!page.sections.length)}</div>;
}
