import { useState } from 'react';
import { BarChart3, CalendarDays, Download, FileText, Globe, Monitor, Settings, ShieldCheck, Smartphone, Users, Zap } from 'lucide-react';
import { AssetSearch, AssetSelect } from './AssetControls';
import { Modal } from './settings/kit';
import type { Asset } from './asset-model';
import { downloadLeads, rangeFor, sampleLeads, sampleSeries } from './funnel-data';
import type { FunnelRange } from './funnel-data';

export function FunnelDateRange({range,change}:{range:FunnelRange;change:(range:FunnelRange)=>void}) {
 const [preset,setPreset]=useState(()=>{const week=rangeFor(7),month=rangeFor(30);return range.start===week.start&&range.end===week.end?'Last 7 Days':range.start===month.start&&range.end===month.end?'Last 30 Days':'Custom Range';}),[custom,setCustom]=useState(false),[start,setStart]=useState(range.start),[end,setEnd]=useState(range.end),[error,setError]=useState('');
 return <div className="fn-date-range"><CalendarDays size={14}/><AssetSelect label="Performance date range" value={preset} options={['Last 30 Days','Last 7 Days','Custom Range']} onChange={value=>{if(value==='Custom Range'){setStart(range.start);setEnd(range.end);setCustom(true);}else{setPreset(value);change(rangeFor(value==='Last 7 Days'?7:30));}}}/>{preset==='Custom Range'&&<small>{range.start} – {range.end}</small>}{custom&&<Modal title="Custom date range" close={()=>setCustom(false)}><form className="aw-modal-body" onSubmit={event=>{event.preventDefault();const days=(Date.parse(end)-Date.parse(start))/86400000+1;if(!Number.isFinite(days)||days<1||days>366){setError('Choose an ordered date range of up to 366 days.');return;}change({start,end});setPreset('Custom Range');setCustom(false);setError('');}}><label>Start date<input aria-label="Start date" type="date" value={start} onChange={event=>setStart(event.target.value)} required/></label><label>End date<input aria-label="End date" type="date" value={end} onChange={event=>setEnd(event.target.value)} required/></label>{error&&<p role="alert" className="aw-error">{error}</p>}<footer><button type="button" className="aw-secondary" onClick={()=>setCustom(false)}>Cancel</button><button className="aw-primary">Apply range</button></footer></form></Modal>}</div>;
}
export function FunnelPerformance({asset,range,change}:{asset:Asset;range:FunnelRange;change:(range:FunnelRange)=>void}) {
 const series=sampleSeries(asset,range),visitors=series.reduce((sum,day)=>sum+day.views,0),leads=series.reduce((sum,day)=>sum+day.conversions,0),bookings=Math.round(leads*.194);
 const metrics=[{label:'Total Visitors',value:visitors.toLocaleString(),growth:24,Icon:Users},{label:'Leads Generated',value:leads.toLocaleString(),growth:18,Icon:FileText},{label:'Bookings',value:bookings.toLocaleString(),growth:32,Icon:CalendarDays},{label:'Conversion Rate',value:(bookings/visitors*100).toFixed(1)+'%',growth:12,Icon:BarChart3}];
 return <section className="aw-panel aw-performance fn-performance"><header><BarChart3 size={18}/><h3>Funnel Performance</h3><span className="fn-demo">Sample data</span><FunnelDateRange range={range} change={change}/></header><div className="aw-metrics">{metrics.map(({label,value,growth,Icon})=><article key={label}><span><Icon size={21}/></span><div><p>{label}</p><div className="aw-metric-value"><strong>{value}</strong><em>↑ {growth}%</em></div><small>vs. previous sample period</small></div></article>)}</div></section>;
}
export function FunnelAnalytics({asset,range,change}:{asset:Asset;range:FunnelRange;change:(range:FunnelRange)=>void}) {
 const series=sampleSeries(asset,range),[hover,setHover]=useState(0),[views,setViews]=useState(true),[conversions,setConversions]=useState(true),selected=series[Math.min(hover,series.length-1)];
 const max=Math.max(...series.map(point=>point.views))*1.1;
 const line=(key:'views'|'conversions')=>series.map((point,index)=>(40+index*640/Math.max(1,series.length-1))+','+(162-point[key]/max*133)).join(' ');
 const visitors=series.reduce((sum,day)=>sum+day.views,0);
 return <div className="fn-analytics"><FunnelPerformance asset={asset} range={range} change={change}/><section className="aw-panel fn-chart"><header><div><h3>Views & conversions</h3><p>{selected.date} · {selected.views} views · {selected.conversions} conversions</p></div><div className="fn-chart-legend"><button aria-pressed={views} onClick={()=>setViews(!views)}><i/>Views</button><button aria-pressed={conversions} onClick={()=>setConversions(!conversions)}><i/>Conversions</button></div></header><svg viewBox="0 0 720 194" role="img" aria-label="Sample daily views and conversions chart">{[0,1,2,3].map(index=><g key={index}><line x1="40" x2="680" y1={30+index*44} y2={30+index*44} stroke="#e2e8f0" strokeDasharray="4 4"/><text x="5" y={34+index*44} fontSize="9" fill="#94a3b8">{Math.round(max*(1-index/3))}</text></g>)}{views&&<polyline points={line('views')} fill="none" stroke="#6366f1" strokeWidth="2.5"/>}{conversions&&<polyline points={line('conversions')} fill="none" stroke="#22c5a3" strokeWidth="2.5"/>}{series.map((point,index)=><rect key={point.date} x={32+index*640/Math.max(1,series.length-1)} y="20" width={Math.max(3,640/series.length)} height="150" fill="transparent" tabIndex={0} aria-label={point.date+': '+point.views+' views, '+point.conversions+' conversions'} onMouseEnter={()=>setHover(index)} onFocus={()=>setHover(index)}><title>{point.date+' · '+point.views+' views · '+point.conversions+' conversions'}</title></rect>)}<text x="40" y="187" fontSize="9" fill="#94a3b8">{range.start}</text><text x="680" y="187" textAnchor="end" fontSize="9" fill="#94a3b8">{range.end}</text></svg></section><div className="fn-analytics-bottom"><section className="aw-panel fn-dropoff"><h3>Step conversion & drop-off</h3>{asset.document.pages.map((page,index)=>{const previous=Math.pow(.64,Math.max(0,index-1)),ratio=Math.pow(.64,index);return <div key={page.id}><span>{index+1}. {page.name}</span><b>{Math.round(visitors*ratio).toLocaleString()}</b><div className="fn-bar"><i style={{width:ratio*100+'%'}}/></div><small>{index?Math.round((1-ratio/previous)*100)+'% drop-off':'100% of visitors'}</small></div>;})}</section><section className="aw-panel fn-sources"><h3>Top traffic sources</h3>{[['Meta Ads',42],['Organic Search',31],['Direct',18],['Referral',9]].map(([name,value])=><div key={name}><Globe size={13}/><span>{name}</span><b>{value}%</b><div className="fn-bar"><i style={{width:value+'%'}}/></div></div>)}</section><section className="aw-panel fn-devices"><h3>Device breakdown</h3><div className="fn-device-ring"><b>64%<small>Mobile</small></b></div><p><Smartphone size={13}/>Mobile <b>64%</b></p><p><Monitor size={13}/>Desktop <b>28%</b></p><p><Monitor size={13}/>Tablet <b>8%</b></p></section></div></div>;
}
export function FunnelLeads({asset}:{asset:Asset}) {
 const [search,setSearch]=useState(''),[tag,setTag]=useState('All tags'),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]);
 const rows=sampleLeads(asset).filter(row=>(row.name+' '+row.email+' '+row.phone+' '+row.source+' '+row.step).toLowerCase().includes(search.toLowerCase())&&(tag==='All tags'||row.tag===tag)),visible=rows.slice(page*6,page*6+6),exported=selected.length?rows.filter(row=>selected.includes(row.id)):rows;
 return <section className="aw-panel fn-leads"><header><div><h3>Captured leads <span>({rows.length})</span></h3><p>Sample contacts · {asset.name}</p></div><span className="fn-demo">Sample data</span></header><div className="aw-controls"><AssetSearch value={search} onChange={value=>{setSearch(value);setPage(0);}} placeholder="Search leads..." shortcut/><AssetSelect label="Lead tag" value={tag} options={['All tags','New lead','Qualified','Booked']} onChange={value=>{setTag(value);setPage(0);}}/><button className="aw-secondary" disabled={!exported.length} onClick={()=>downloadLeads(exported,asset.id)}><Download size={14}/>Export {selected.length?'selected':'leads'}</button>{(search||tag!=='All tags')&&<button className="aw-text-button" onClick={()=>{setSearch('');setTag('All tags');setPage(0);}}>Clear filters</button>}</div><div className="aw-table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select visible leads" checked={!!visible.length&&visible.every(row=>selected.includes(row.id))} onChange={event=>setSelected(current=>event.target.checked?[...new Set([...current,...visible.map(row=>row.id)])]:current.filter(id=>!visible.some(row=>row.id===id)))}/></th>{['Name','Email','Phone','Step Captured','Source','Date','Tag'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={'Select '+row.name} checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/></td><td><b>{row.name}</b></td><td>{row.email}</td><td>{row.phone}</td><td>{row.step}</td><td>{row.source}</td><td>{row.date}</td><td><span className={'fn-tag '+row.tag.toLowerCase().replace(' ','-')}>{row.tag}</span></td></tr>)}</tbody></table></div>{!rows.length&&<div className="fn-no-results"><Users size={24}/><h3>No matching leads</h3><p>Try another name, source, or tag.</p></div>}<footer><span>{rows.length?Math.min(page*6+1,rows.length):0}–{Math.min((page+1)*6,rows.length)} of {rows.length} leads</span><div><button className="aw-secondary" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button className="aw-secondary" disabled={(page+1)*6>=rows.length} onClick={()=>setPage(page+1)}>Next</button></div></footer></section>;
}
export function FunnelIntegrations({asset,update}:{asset:Asset;update:(id:string,change:(asset:Asset)=>Asset)=>void}) {
 const [config,setConfig]=useState(''),[value,setValue]=useState('');
 const tools=[{name:'Meta Pixel',description:'Measure ad conversions and retarget visitors.',icon:'M',field:'Pixel ID',default:'928174620451'},{name:'Stripe',description:'Accept payments and track successful checkouts.',icon:'S',field:'Account label',default:'FitZone workspace'},{name:'Google Analytics 4',description:'Understand visitor behavior across every step.',icon:'G',field:'Measurement ID',default:'G-GOS1234567'},{name:'Zapier',description:'Connect funnel events to your business tools.',icon:'Z',field:'Workflow name',default:'New lead → CRM'},{name:'Mailchimp',description:'Send new leads to your email audience.',icon:'C',field:'Audience ID',default:'fitness-coaching'}];
 const activeTool=tools.find(tool=>tool.name===config);
 return <section className="fn-integrations"><header><div><h3>Connected tools</h3><p>Configure sample connections for this funnel.</p></div><span className="fn-demo">Sample connections</span></header><div className="fn-integration-grid">{tools.map((tool,index)=>{const state=asset.integrations?.[tool.name],active=state?.enabled??index!==3;return <article className="aw-panel" key={tool.name}><header><span className={'fn-tool-logo tool-'+index}>{tool.icon}</span><button role="switch" aria-label={'Enable '+tool.name} aria-checked={active} className={'aw-default '+(active?'active':'')} onClick={()=>update(asset.id,current=>({...current,integrations:{...current.integrations,[tool.name]:{enabled:!active,configuration:state?.configuration??tool.default}}}))}><span/></button></header><h3>{tool.name}</h3><p>{tool.description}</p><footer><span className={'fn-connection '+(active?'active':'')}><ShieldCheck size={12}/>{active?'Active':'Paused'}</span><button className="aw-secondary" onClick={()=>{setConfig(tool.name);setValue(state?.configuration??tool.default);}}><Settings size={13}/>Configure</button></footer></article>;})}</div><div className="fn-integration-note"><Zap size={16}/>Sample connections do not send events to external services.</div>{activeTool&&<Modal title={'Configure '+activeTool.name} close={()=>setConfig('')}><form className="aw-modal-body" onSubmit={event=>{event.preventDefault();update(asset.id,current=>({...current,integrations:{...current.integrations,[activeTool.name]:{enabled:current.integrations?.[activeTool.name]?.enabled??tools.indexOf(activeTool)!==3,configuration:value.trim()}}}));setConfig('');}}><p>Settings are saved to this funnel's sample connection.</p><label>{activeTool.field}<input aria-label={activeTool.field} value={value} onChange={event=>setValue(event.target.value)} required maxLength={120}/></label><footer><button type="button" className="aw-secondary" onClick={()=>setConfig('')}>Cancel</button><button className="aw-primary">Save configuration</button></footer></form></Modal>}</section>;
}
