import React from 'react';
import { ArrowRight, ArrowUp, ArrowUpDown, Bell, Box, CalendarClock, CalendarDays, Check, ChevronDown, Clock3, CreditCard, ExternalLink, FileText, Grid2X2, Layers3, Link2, LockKeyhole, MonitorPlay, MoreHorizontal, Plus, Search, Settings, ShieldCheck, ShoppingBag, ShoppingCart, SlidersHorizontal, Tag, UserRound, Users, UsersRound, UserRoundCheck, X } from 'lucide-react';
import aiCourseImg from '../assets/products/ai-course.jpg';
import socialPackImg from '../assets/products/social-pack.jpg';
import strategyCallImg from '../assets/products/strategy-call.jpg';
import whatsappSetupImg from '../assets/products/whatsapp-setup.jpg';
import funnelSetupImg from '../assets/products/funnel-setup.jpg';
import agencyKitImg from '../assets/products/agency-kit.jpg';
import gosProImg from '../assets/products/gos-pro.jpg';
import growthBundleImg from '../assets/products/growth-bundle.jpg';
import './products-payments.css';
import './products-payments-overrides.css';

type StatKind='sales'|'revenue'|'bookings'|'members';
type Product={id:string;name:string;type:string;price:string;stats:Array<[StatKind,string]>;status:'Active'|'Inactive';sales:string;revenue:string;art:string;image?:string;tag:string;description:string};
const statIcons:Record<StatKind,React.ElementType>={sales:UsersRound,revenue:Clock3,bookings:CalendarDays,members:UserRound};
type Props={notify:(message:string)=>void;showModal?:boolean;setShowModal?:(show:boolean)=>void};
const seedProducts:Product[]=[
 {id:'ai-course',name:'Complete AI Marketing Course',type:'Online Course',price:'€297',stats:[['sales','124 sales'],['revenue','€36,828 revenue']],status:'Active',sales:'124',revenue:'€36,828',art:'course',image:aiCourseImg,tag:'Online Course',description:'Learn how to create, market and sell digital products using AI. Step by step system with real examples and templates.'},
 {id:'social-pack',name:'Social Media Templates Pack',type:'Digital Product',price:'€47',stats:[['sales','312 sales'],['revenue','€14,664 revenue']],status:'Active',sales:'312',revenue:'€14,664',art:'templates',image:socialPackImg,tag:'Digital Product',description:'A ready-to-use library of branded social templates for growing businesses.'},
 {id:'strategy-call',name:'1-on-1 Strategy Call',type:'Service',price:'€97',stats:[['bookings','48 bookings']],status:'Active',sales:'48',revenue:'€4,656',art:'speaker',image:strategyCallImg,tag:'Service',description:'A focused strategy session to turn your next business goal into a practical plan.'},
 {id:'whatsapp-setup',name:'WhatsApp Automation Setup',type:'Service',price:'€497',stats:[['sales','36 sales']],status:'Active',sales:'36',revenue:'€17,892',art:'whatsapp',image:whatsappSetupImg,tag:'Service',description:'Done-with-you setup for WhatsApp lead capture, routing, and automated follow-up.'},
 {id:'funnel-setup',name:'Done-For-You Funnel Setup',type:'Service',price:'€497',stats:[['sales','36 sales']],status:'Inactive',sales:'36',revenue:'€17,892',art:'funnel',image:funnelSetupImg,tag:'Service',description:'A conversion-focused funnel built and connected to your business tools.'},
 {id:'agency-kit',name:'Agency Starter Kit',type:'Digital Product',price:'€67',stats:[['sales','210 sales']],status:'Active',sales:'210',revenue:'€14,070',art:'agency',image:agencyKitImg,tag:'Digital Product',description:'Systems, templates, and resources to launch and grow a modern agency.'},
 {id:'gos-pro',name:'GOS Pro Membership',type:'Subscription',price:'€29 / month',stats:[['members','86 members']],status:'Active',sales:'86',revenue:'€2,494',art:'membership',image:gosProImg,tag:'Subscription',description:'A monthly membership for tools, training, and business growth support.'},
 {id:'growth-bundle',name:'Business Growth Bundle',type:'Bundle',price:'€197',stats:[['sales','54 sales']],status:'Active',sales:'54',revenue:'€10,638',art:'bundle',image:growthBundleImg,tag:'Bundle',description:'A curated bundle of digital tools and resources for business growth.'},
];
const productTabs=[['Products',ShoppingBag],['Orders',FileText],['Customers',Users],['Payments',CreditCard],['Discounts',SlidersHorizontal],['Settings',Settings]] as const;
const metricData=[['All Products','24','All your products',Box,'violet'],['Digital Products','8','Courses, templates, files',FileText,'blue'],['Services','6','Calls, consulting, coaching',UserRoundCheck,'green'],['Subscriptions','4','Memberships, recurring',CalendarClock,'orange'],['Bundles','6','Product packages',Layers3,'pink']] as const;

export const ProductsPayments:React.FC<Props>=({notify,showModal=false,setShowModal})=>{
 const [products,setProducts]=React.useState(seedProducts);const[selectedId,setSelectedId]=React.useState('ai-course');const[selectedTab,setSelectedTab]=React.useState('Products');const[detailTab,setDetailTab]=React.useState('Overview');const[search,setSearch]=React.useState('');const[type,setType]=React.useState('All Types');const[status,setStatus]=React.useState('All Status');const[sort,setSort]=React.useState('Newest First');const[view,setView]=React.useState<'Grid'|'List'>('Grid');const[filterMetric,setFilterMetric]=React.useState('All Products');const[modal,setModal]=React.useState(false);const[newName,setNewName]=React.useState('');const[newPrice,setNewPrice]=React.useState('');const[newType,setNewType]=React.useState('Digital Product');const[paymentOptions,setPaymentOptions]=React.useState(['One-time payment']);const[description,setDescription]=React.useState(seedProducts[0].description);const[editingDescription,setEditingDescription]=React.useState(false);
 const selected=products.find(p=>p.id===selectedId)??products[0];
 React.useEffect(()=>{if(showModal)setModal(true)},[showModal]);
 React.useEffect(()=>{if(selected)setDescription(selected.description)},[selectedId]);
 const closeModal=()=>{setModal(false);setShowModal?.(false)};
 const displayed=products.filter(p=>(type==='All Types'||p.type===type)&&(status==='All Status'||p.status===status)&&(filterMetric==='All Products'||p.type===filterMetric)&&`${p.name} ${p.type}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='A to Z'?a.name.localeCompare(b.name):sort==='Price: Low to High'?Number(a.price.replace(/[^0-9.]/g,''))-Number(b.price.replace(/[^0-9.]/g,'')):0);
 const createProduct=()=>{if(!newName.trim()||!newPrice.trim()){notify('Add a product name and price first.');return}const item:Product={id:`product-${Date.now()}`,name:newName.trim(),type:newType,price:newPrice.startsWith('€')?newPrice:`€${newPrice}`,stats:[['sales','0 sales']],status:'Active',sales:'0',revenue:'€0',art:newType==='Service'?'speaker':newType==='Subscription'?'membership':newType==='Bundle'?'bundle':'templates',tag:newType,description:'Add a description for this product.'};setProducts(p=>[item,...p]);setSelectedId(item.id);setSelectedTab('Products');setDetailTab('Overview');setNewName('');setNewPrice('');closeModal();notify('Product created.')};
 const toggleStatus=(item:Product)=>setProducts(current=>current.map(p=>p.id===item.id?{...p,status:p.status==='Active'?'Inactive':'Active'}:p));
 return <main className="pp-page">
  <header className="pp-header"><span className="pp-header-icon"><ShoppingBag size={22}/></span><div><h1>Products &amp; Payments</h1><p>Create and sell digital products, services and subscriptions.</p></div><div className="pp-header-right"><label className="pp-global-search"><Search size={15}/><input placeholder="Search products, orders, customers..."/></label><button className="pp-bell" aria-label="Notifications" onClick={()=>notify('You are all caught up.')}><Bell size={19}/><i/></button><div className="pp-user"><img src="https://i.pravatar.cc/80?img=12" alt="Mohamed Joe"/><span><b>Mohamed Joe</b><small>Business Owner</small></span><ChevronDown size={14}/></div></div></header>
  <div className="pp-tabs">{productTabs.map(([name,Icon])=><button key={name} className={selectedTab===name?'active':''} onClick={()=>{setSelectedTab(name);if(name!=='Products')notify(`${name} view selected.`)}}><Icon size={15}/>{name}</button>)}<button className="pp-create" onClick={()=>setModal(true)}><Plus size={15}/> Create Product <ChevronDown size={13}/></button></div>
  {selectedTab==='Products'?<>
   <section className="pp-metrics">{metricData.map(([label,value,note,Icon,tone])=><button key={label} className={`pp-metric ${tone} ${filterMetric===label?'selected':''}`} onClick={()=>{setFilterMetric(label==='All Products'?'All Products':label==='Digital Products'?'Digital Product':label==='Services'?'Service':label==='Subscriptions'?'Subscription':label==='Bundles'?'Bundle':'All Products');setType(label==='All Products'?'All Types':label==='Digital Products'?'Digital Product':label==='Services'?'Service':label==='Subscriptions'?'Subscription':'Bundle')}}><span><Icon size={23}/></span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></button>)}</section>
   <div className="pp-workspace"><section className="pp-catalog"><div className="pp-toolbar"><label className="pp-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/></label><ProfessionalSelect value={type} options={['All Types','Online Course','Digital Product','Service','Subscription','Bundle']} onChange={v=>{setType(v);setFilterMetric(v==='All Types'?'All Products':v)}}/><ProfessionalSelect value={status} options={['All Status','Active','Inactive','Draft']} onChange={setStatus}/><ProfessionalSelect icon={ArrowUpDown} value={sort} options={['Newest First','A to Z','Price: Low to High']} onChange={setSort}/><span className="pp-toolbar-divider" aria-hidden="true"/><div className="pp-view-toggle"><button className={view==='Grid'?'active':''} aria-label="Grid view" onClick={()=>setView('Grid')}><Grid2X2 size={16}/></button><button className={view==='List'?'active':''} aria-label="List view" onClick={()=>setView('List')}><RowsIcon/></button></div></div><div className={`pp-products ${view==='List'?'list':''}`}>{displayed.map(item=><ProductCard key={item.id} item={item} selected={item.id===selectedId} onSelect={()=>setSelectedId(item.id)} onToggle={()=>toggleStatus(item)} notify={notify}/>)}</div></section>
    <aside className="pp-inspector"><div className="pp-inspector-head"><div className="pp-thumb-small">{selected.image?<img src={selected.image} alt={`${selected.name} thumbnail`}/>:<Artwork kind={selected.art}/>}</div><div className="pp-inspector-name"><b>{selected.name}</b><span className={`pp-status ${selected.status.toLowerCase()}`}>{selected.status}</span></div><button className="pp-close" onClick={()=>notify('Product inspector remains docked for quick editing.')}><X size={17}/></button></div><nav className="pp-detail-tabs">{['Overview','Content','Pricing','Automation','Settings'].map(t=><button className={detailTab===t?'active':''} key={t} onClick={()=>setDetailTab(t)}>{t}</button>)}</nav><div className="pp-inspector-scroll">{detailTab==='Overview'?<><div className="pp-quick-metrics"><div className="price"><span><Tag size={16}/></span><b>{selected.price}</b><small>Price</small></div><div className="sales"><span><ShoppingCart size={16}/></span><b>{selected.sales}</b><small>Total Sales</small></div><div className="revenue"><span><Clock3 size={16}/></span><b>{selected.revenue}</b><small>Total Revenue</small></div></div><div className="pp-description-head"><b>Description</b><button onClick={()=>setEditingDescription(v=>!v)}>{editingDescription?'Done':'Edit'}</button></div>{editingDescription?<textarea className="pp-description-editor" value={description} onChange={e=>setDescription(e.target.value)}/>:<p className="pp-description">{description}</p>}<label className="pp-detail-field">Product Type<ProfessionalSelect icon={MonitorPlay} value={selected.type==='Online Course'?'Online Course':selected.type} options={['Online Course','Digital Product','Service','Subscription','Bundle']} onChange={value=>setProducts(list=>list.map(p=>p.id===selected.id?{...p,type:value,tag:value}:p))}/></label><label className="pp-detail-field">Access<ProfessionalSelect icon={LockKeyhole} value="Lifetime Access" options={['Lifetime Access','12 months','Subscription access','Download only']} onChange={v=>notify(`Access set to ${v}.`)}/></label><div className="pp-payment-options"><b>Payment Options</b>{[['One-time payment',selected.price],['Payment plan','3 × €97'],['Subscription','€29 / month']].map(([name,price])=><label key={name}><input type="checkbox" checked={paymentOptions.includes(name)} onChange={e=>setPaymentOptions(current=>e.target.checked?[...current,name]:current.filter(item=>item!==name))}/><span>{name}</span><em>{price}</em></label>)}</div></>:<InspectorTab tab={detailTab} item={selected} notify={notify} toggleStatus={()=>toggleStatus(selected)}/>}</div><footer className="pp-inspector-actions"><button onClick={()=>notify(`Sales page preview opened for ${selected.name}.`)}><Link2 size={14}/> View Sales Page</button><button className="primary" onClick={()=>notify(`Edit product form opened for ${selected.name}.`)}>Edit Product <ArrowRight size={14}/></button></footer></aside>
   </div>
  </>:<SecondaryModule tab={selectedTab} notify={notify}/>}
  {modal&&<div className="pp-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&closeModal()}><section className="pp-modal" role="dialog" aria-modal="true"><header><span className="pp-modal-icon"><Plus size={18}/></span><div><h2>Create a product</h2><p>Add a product to your catalog and choose its starting price.</p></div><button onClick={closeModal}><X size={17}/></button></header><label>Product name<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} placeholder="e.g. Social Media Templates Pack"/></label><div className="pp-modal-grid"><label>Product type<ProfessionalSelect value={newType} options={['Online Course','Digital Product','Service','Subscription','Bundle']} onChange={setNewType}/></label><label>Price<input value={newPrice} onChange={e=>setNewPrice(e.target.value)} placeholder="€ 0.00"/></label></div><div className="pp-modal-note"><ShieldCheck size={14}/> Payment processing remains connected to your selected provider.</div><footer><button onClick={closeModal}>Cancel</button><button className="primary" onClick={createProduct}>Create product <ArrowRight size={14}/></button></footer></section></div>}
 </main>
};

function ProductCard({item,selected,onSelect,onToggle,notify}:{item:Product;selected:boolean;onSelect:()=>void;onToggle:()=>void;notify:(s:string)=>void}){return <article className={`pp-product-card ${selected?'selected':''}`}><button className="pp-art" onClick={onSelect} aria-label={`View ${item.name}`}>{item.image?<img src={item.image} alt={`${item.name} thumbnail`} loading="lazy" draggable={false}/>:<Artwork kind={item.art}/>}<span className="pp-card-more" onClick={e=>{e.stopPropagation();notify(`${item.name} actions opened.`)}}><MoreHorizontal size={17}/></span></button><div className="pp-card-info"><span className={`pp-type-tag ${item.type.toLowerCase().replaceAll(' ','-')}`}>{item.tag}</span><button className="pp-product-title" onClick={onSelect}>{item.name}</button><b className="pp-price">{item.price}</b><div className="pp-product-metric">{item.stats.map(([kind,text])=>{const StatIcon=statIcons[kind];return <span key={kind}><StatIcon size={12}/>{text}</span>})}</div><div className="pp-card-footer"><button className={`pp-status ${item.status.toLowerCase()}`} onClick={onToggle}><ArrowUp size={11} strokeWidth={2.6}/>{item.status}</button><button className="pp-open" title="Open sales page" aria-label={`Open sales page for ${item.name}`} onClick={()=>notify(`Sales page opened for ${item.name}.`)}><ExternalLink size={15}/></button></div></div></article>}
function Artwork({kind}:{kind:string}){return <div className={`pp-artwork ${kind}`}><div className="art-glow"/><div className="art-phone"><span/><i/><i/><i/></div>{kind==='course'?<><span className="art-arabic">تسويق ذكي<br/><b>AI</b> للمستقبل</span><span className="art-person">MJ</span><small>GOING<br/>FURTHER</small></>:kind==='templates'?<><span className="art-neon-title">SOCIAL<br/>TEMPLATES</span><div className="art-phone second"><span/><i/><i/><i/></div><b className="art-sticker">120+</b></>:kind==='speaker'?<><span className="art-speaker">MJ</span><div className="art-callout"><CalendarClock size={18}/></div><small>STRATEGY<br/>SESSION</small></>:kind==='whatsapp'?<><span className="art-arabic">تنفيذ<br/>وتحسين</span><span className="art-wa">◉</span><small>WHATSAPP<br/>AUTOMATION</small></>:kind==='funnel'?<><div className="art-dashboard"><b>GOS</b><i/><i/><i/><span>Leads +28%</span></div><span className="art-mini-phone"/></>:kind==='agency'?<><span className="art-agency-title">Agency<br/>Starter Kit</span><div className="art-dashboard"><b>GOS</b><i/><i/><span>Launch system</span></div></>:kind==='membership'?<><span className="art-crown">♛</span><b className="art-membership">Premium<br/>Membership</b><small>GOS PRO</small></>:<><div className="art-phone"><span/><i/><i/><i/></div><div className="art-phone second"><span/><i/><i/><i/></div><span className="art-bundle">GROW</span></>}</div>}
function ProfessionalSelect({value,options,onChange,icon:Icon}:{value:string;options:string[];onChange:(v:string)=>void;icon?:React.ElementType}){const[open,setOpen]=React.useState(false);const ref=React.useRef<HTMLDivElement>(null);React.useEffect(()=>{const fn=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[]);return <div className="pp-select" ref={ref}><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span className="pp-select-value">{Icon&&<Icon size={14} className="pp-select-icon"/>}<span>{value}</span></span><ChevronDown size={14}/></button>{open&&<div className="pp-select-menu" role="listbox">{options.map(option=><button type="button" role="option" aria-selected={option===value} className={option===value?'active':''} key={option} onClick={()=>{onChange(option);setOpen(false)}}>{option}{option===value&&<Check size={13}/>}</button>)}</div>}</div>}
function InspectorTab({tab,item,notify,toggleStatus}:{tab:string;item:Product;notify:(s:string)=>void;toggleStatus:()=>void}){if(tab==='Content')return <div className="pp-tab-panel"><h3>Product content</h3><p>Manage the materials your customers receive after purchase.</p><div className="pp-content-item"><FileText size={16}/><span><b>{item.name} materials</b><small>Course files · 12 resources</small></span><button onClick={()=>notify('Content library opened.')}>Manage</button></div><button className="pp-add-content" onClick={()=>notify('Choose files to add to product content.')}><Plus size={14}/> Add content</button></div>;if(tab==='Pricing')return <div className="pp-tab-panel"><h3>Pricing &amp; offers</h3><p>Manage the price and payment options for this offer.</p><label>Base price<input defaultValue={item.price}/></label><label>Currency<ProfessionalSelect value="EUR · Euro" options={['EUR · Euro','USD · US Dollar','GBP · Pound Sterling']} onChange={v=>notify(`Currency set to ${v}.`)}/></label><button className="pp-inline-save" onClick={()=>notify('Pricing changes saved.')}>Save pricing</button></div>;if(tab==='Automation')return <div className="pp-tab-panel"><h3>Purchase automations</h3><p>Actions that run after a successful payment.</p>{['Grant product access','Create or update CRM lead','Send purchase confirmation','Start customer follow-up'].map((label,i)=><label className="pp-auto-row" key={label}><span><b>{label}</b><small>{['Access delivery','Canonical contact record','Email receipt','AI Follow-up'][i]}</small></span><input type="checkbox" defaultChecked={i<3}/></label>)}</div>;return <div className="pp-tab-panel"><h3>Product settings</h3><p>Visibility and product lifecycle controls.</p><label>Product status<ProfessionalSelect value={item.status} options={['Active','Inactive','Draft']} onChange={()=>toggleStatus()}/></label><label>Sales page URL<input readOnly value={`gos.com/products/${item.id}`}/></label><button className="pp-inline-save" onClick={()=>notify('Product settings saved.')}>Save settings</button></div>}
function SecondaryModule({tab,notify}:{tab:string;notify:(s:string)=>void}){const rows=tab==='Orders'?[['#ORD-1048','Sarah Ahmed','Complete AI Marketing Course','€297','Paid'],['#ORD-1047','Omar Khaled','Social Media Templates Pack','€47','Paid'],['#ORD-1046','Lina Mansour','GOS Pro Membership','€29','Pending']]:tab==='Customers'?[['Sarah Ahmed','sarah@northstar.co','3 orders','€594','Active'],['Omar Khaled','omar@orbitlabs.io','2 orders','€344','Active'],['Lina Mansour','lina@brightpath.com','1 order','€97','Active']]:tab==='Payments'?[['PAY-4401','Sarah Ahmed','Stripe','€297','Succeeded'],['PAY-4400','Omar Khaled','Stripe','€47','Succeeded'],['PAY-4399','Lina Mansour','PayPal','€97','Refunded']]:tab==='Discounts'?[['WELCOME10','10% off','All products','84 uses','Active'],['GROWTH25','€25 off','Business Growth Bundle','16 uses','Active']]:[];return <section className="pp-secondary-view"><div className="pp-secondary-heading"><div><h2>{tab}</h2><p>Manage your {tab.toLowerCase()} across products and payments.</p></div><button onClick={()=>notify(`Create ${tab.slice(0,-1).toLowerCase()} form opened.`)}><Plus size={14}/> Create {tab.slice(0,-1)}</button></div>{tab==='Settings'?<div className="pp-settings-cards">{[['Store details','Manage the name, currency, and customer experience for your store.',Settings],['Payment providers','Connect Stripe, PayPal, and other payment methods.',CreditCard],['Tax & receipts','Configure tax collection and customer receipts.',FileText],['Checkout preferences','Set checkout, fulfillment, and access defaults.',SlidersHorizontal]].map(([title,description,Icon])=><button key={String(title)} onClick={()=>notify(`${title} settings opened.`)}><span><Icon size={18}/></span><b>{String(title)}</b><small>{String(description)}</small><ArrowRight size={14}/></button>)}</div>:<div className="pp-secondary-table"><div>{(tab==='Orders'?['Order','Customer','Product','Total','Status']:tab==='Customers'?['Customer','Email','Orders','Lifetime value','Status']:tab==='Payments'?['Payment','Customer','Provider','Amount','Status']:['Code','Offer','Applies to','Uses','Status']).map(h=><b key={h}>{h}</b>)}</div>{rows.map(row=><div key={row[0]}>{row.map((cell,i)=><span key={i}>{i===row.length-1?<em className={`pp-secondary-status ${cell.toLowerCase()}`}>{cell}</em>:cell}</span>)}</div>)}</div>}</section>}
function RowsIcon(){return <span className="pp-rows-icon"><i/><i/><i/></span>}
