import React from 'react';
import { CommerceSelect } from '../../components/ui/CommerceSelect';
import { CheckCircle2, CreditCard, FileText, GripVertical, LockKeyhole, Package, Plus, Repeat2, Trash2 } from 'lucide-react';
import type { Billing, ProductExperience } from './model';
import { productKind } from './model';
import type { FormProps } from './TypeForms';
import { Card, Field, Select, Toggle } from './primitives';
function money(amount: number, currency: string) { return new Intl.NumberFormat('en-IE', { style: 'currency', currency, minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(amount); }
function currencySymbol(currency: string) { return new Intl.NumberFormat('en-IE', { style: 'currency', currency }).formatToParts(0).find(part => part.type === 'currency')?.value ?? currency; }
function intervalUnit(interval: string) { return interval === 'Yearly' ? 'year' : interval === 'Quarterly' ? 'quarter' : 'month'; }
export function CardSwitch({ label, checked, onChange, disabled }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled: boolean }) { return <div className="pricing-card-switch"><Toggle {...{ label, checked, onChange, disabled }}/></div>; }
function Currency({ config: c, configure, editing, label }: FormProps & { label?: string }) { return <CommerceSelect label={label} disabled={!editing} value={c.currency} options={[{ value: 'EUR', label: 'EUR (€)' }, { value: 'USD', label: 'USD ($)' }, { value: 'GBP', label: 'GBP (£)' }]} onChange={currency => configure({ currency: currency as typeof c.currency })}/>; }
export function PricingForm(props: FormProps) {
  const { config: c, experience: e, configure, customize, editing, product } = props;
  function billing(value: Billing) { configure({ billing: value, amount: value === 'One-time' ? e.oneTimeAmount : value === 'Payment plan' ? e.installmentAmount : e.recurringAmount }); if (value === 'Payment plan') customize({ planEnabled: true }); if (value === 'Subscription') customize({ recurringEnabled: true }); }
  const subscription = productKind(product.type) === 'subscription';
  return <div className="tw-pricing-form">
    <Card title="Pricing Type" subtitle="Choose how you want to sell this product."><div className="tw-pricing-types">{([['One-time', 'One-time payment', 'Single payment, lifetime access', CreditCard], ['Payment plan', 'Payment plan', 'Split into multiple payments', FileText], ['Subscription', 'Subscription', 'Recurring payments (monthly/yearly)', Repeat2]] as const).map(([value, title, hint, Icon]) => <button key={value} disabled={!editing || subscription && value !== 'Subscription'} aria-pressed={c.billing === value} className={c.billing === value ? 'selected' : ''} onClick={() => billing(value)}><Icon size={18}/><span><b>{title}</b><small>{hint}</small></span>{c.billing === value && <span className="pricing-active"><CheckCircle2 size={12}/><span>Active</span></span>}</button>)}</div></Card>
    <Card title="Pricing Details" subtitle="Set your price and currency."><div className="pricing-amounts with-compare"><Field label="Price *"><input type="number" min="0" step="0.01" disabled={!editing} value={subscription ? e.recurringAmount : e.oneTimeAmount} onChange={event => { const amount = Number(event.target.value); customize(subscription ? { recurringAmount: amount } : { oneTimeAmount: amount }); if (subscription || c.billing === 'One-time') configure({ amount }); }}/></Field><Field label="Currency"><Currency {...props}/></Field>{<><Field label="Compare Price (Optional)"><input type="number" min="0" step="0.01" disabled={!editing} value={e.comparePrice} onChange={event => customize({ comparePrice: Number(event.target.value) })}/></Field><Field label="Currency"><Currency {...props} label="Compare currency"/></Field></>}</div><Toggle disabled={!editing} label="Show compare price (show as discounted)" checked={e.showComparePrice} onChange={showComparePrice => customize({ showComparePrice })}/></Card>
    <Card title="Payment Plan (Optional)" subtitle="Let customers pay in multiple installments." action={<CardSwitch disabled={!editing || c.billing === 'Payment plan'} label="Enable payment plan offer" checked={e.planEnabled || c.billing === 'Payment plan'} onChange={planEnabled => customize({ planEnabled })}/>}><div className="tw-three-fields"><Field label="Number of Payments"><input type="number" min="2" step="1" disabled={!editing || !e.planEnabled && c.billing !== 'Payment plan'} value={c.installments} onChange={event => configure({ installments: Number(event.target.value) })}/></Field><Field label="Payment Interval"><Select disabled={!editing || !e.planEnabled && c.billing !== 'Payment plan'} value={e.paymentInterval} options={['Monthly', 'Quarterly', 'Yearly']} onChange={paymentInterval => customize({ paymentInterval: paymentInterval as ProductExperience['paymentInterval'] })}/></Field><Field label="Payment Amount"><span className="pricing-suffix pricing-money-field"><i aria-hidden="true">{currencySymbol(c.currency)}</i><input type="number" min="0.01" step="0.01" disabled={!editing || !e.planEnabled && c.billing !== 'Payment plan'} value={e.installmentAmount} onChange={event => { const amount = Number(event.target.value); customize({ installmentAmount: amount }); if (c.billing === 'Payment plan') configure({ amount }); }}/><small>/ {intervalUnit(e.paymentInterval)}</small></span></Field></div></Card>
    <Card title="Subscription (Optional)" subtitle="Charge customers automatically on a recurring basis." action={<CardSwitch disabled={!editing || c.billing === 'Subscription'} label="Enable recurring subscription offer" checked={e.recurringEnabled || c.billing === 'Subscription'} onChange={recurringEnabled => customize({ recurringEnabled })}/>}><div className="tw-three-fields"><Field label="Subscription Price"><span className="pricing-money-field"><i aria-hidden="true">{currencySymbol(c.currency)}</i><input type="number" min="0.01" step="0.01" disabled={!editing || !e.recurringEnabled && c.billing !== 'Subscription'} value={e.recurringAmount} onChange={event => { const amount = Number(event.target.value); customize({ recurringAmount: amount }); if (c.billing === 'Subscription') configure({ amount }); }}/></span></Field><Field label="Billing Interval"><Select disabled={!editing || !e.recurringEnabled && c.billing !== 'Subscription'} value={c.frequency} options={['Monthly', 'Quarterly', 'Yearly']} onChange={frequency => configure({ frequency: frequency as typeof c.frequency })}/></Field><Field label="Trial Period (Optional)"><span className="pricing-suffix"><input type="number" min="0" step="1" disabled={!editing || !e.recurringEnabled && c.billing !== 'Subscription'} value={c.trialDays} onChange={event => configure({ trialDays: Number(event.target.value) })}/><small>days</small></span></Field></div><details className="pricing-extra"><summary>Cancellation settings</summary><Field label="Cancellation Trigger"><Select disabled={!editing} value={c.cancellation} options={['End of billing period', 'Immediately']} onChange={cancellation => configure({ cancellation: cancellation as typeof c.cancellation })}/></Field></details></Card>
  </div>;
}
export function CheckoutPreview({ product: p, config: c, experience: e, onCheckout, showOptionalOffers = false }: FormProps & { onCheckout: (billing: Billing) => void; showOptionalOffers?: boolean }) {
  const [choice, setChoice] = React.useState<Billing | null>(null);
  const group = React.useId();
  const kind = productKind(p.type);
  const options: Array<{ billing: Billing; name: string; description: string; price: string }> = kind === 'subscription' ? [] : [{ billing: 'One-time', name: 'One-time payment', description: `${c.access} · One payment`, price: money(e.oneTimeAmount, c.currency) }];
  if (kind !== 'subscription' && (showOptionalOffers || e.planEnabled || c.billing === 'Payment plan')) options.push({ billing: 'Payment plan', name: `${c.installments} ${e.paymentInterval.toLowerCase()} payments`, description: `${c.installments} payments · Total ${money(e.installmentAmount * c.installments, c.currency)}`, price: `${money(e.installmentAmount, c.currency)} / ${intervalUnit(e.paymentInterval)}` });
  if (showOptionalOffers || e.recurringEnabled || c.billing === 'Subscription') options.push({ billing: 'Subscription', name: `${c.frequency} subscription`, description: c.trialDays ? `${c.trialDays}-day trial · Cancel anytime` : 'Cancel anytime', price: `${money(e.recurringAmount, c.currency)} / ${intervalUnit(c.frequency)}` });
  const selected = choice && options.some(option => option.billing === choice) && (choice === 'One-time' || choice === c.billing || (choice === 'Payment plan' ? e.planEnabled : e.recurringEnabled)) ? choice : c.billing;
  return <Card title="Pricing Options Preview" subtitle="This is how your pricing will appear on the checkout page." className="tw-checkout-preview"><div className="tw-checkout-product">{p.image ? <img src={p.image} alt={p.name}/> : <Package size={30}/>}<div><b>{p.name || 'Your product name'}</b><small>{e.shortDescription || p.type}</small></div></div>{options.map(option => <label className={`tw-checkout-option${selected === option.billing ? ' selected' : ''}`} key={option.billing}><input type="radio" name={group} disabled={option.billing !== 'One-time' && option.billing !== c.billing && !(option.billing === 'Payment plan' ? e.planEnabled : e.recurringEnabled)} title={option.billing !== 'One-time' && option.billing !== c.billing && !(option.billing === 'Payment plan' ? e.planEnabled : e.recurringEnabled) ? 'Enable this pricing option to select it' : undefined} checked={selected === option.billing} onChange={() => setChoice(option.billing)}/><span><b>{option.name}</b>{option.billing === c.billing && <em className="pricing-popular">Best Value</em>}<small>{option.description}</small></span><strong>{option.price}{option.billing === 'One-time' && e.showComparePrice && <del>{money(e.comparePrice, c.currency)}</del>}</strong></label>)}<button className="cw-button primary cw-wide" onClick={() => onCheckout(selected)}>{kind === 'course' ? 'Enroll Now' : kind === 'service' ? 'Book Now' : kind === 'subscription' ? 'Join Membership' : 'Get Access'}</button><div className="tw-secure pricing-payment-badges">{e.checkout.secure && <small><LockKeyhole size={12}/> Secure checkout</small>}{e.paymentMethods.map(method => <span key={method} className={`payment-${method.toLowerCase().replace(' ', '-')}`}>{method === 'Mastercard' ? <><i/><i/><span className="pricing-sr">Mastercard</span></> : method}</span>)}</div></Card>;
}
export function CheckoutSettings({ config: c, experience: e, configure, customize, editing }: FormProps) {
  function checkout(key: keyof ProductExperience['checkout'], value: boolean) { customize({ checkout: { ...e.checkout, [key]: value } }); }
  return <Card title="Checkout Settings">{([['secure', 'Enable secure checkout page'], ['collectInfo', 'Collect customer information'], ['requirePhone', 'Require phone number'], ['guest', 'Enable guest checkout'], ['testimonials', 'Show testimonials on checkout']] as const).map(([key, label]) => <Toggle key={key} disabled={!editing} label={label} checked={e.checkout[key]} onChange={value => checkout(key, value)}/>)}<details className="pricing-extra"><summary>Payment methods & custom fields</summary><div className="pricing-methods">{(['Visa', 'Mastercard', 'PayPal', 'Apple Pay', 'Google Pay'] as const).map(method => <label key={method}><input type="checkbox" disabled={!editing} checked={e.paymentMethods.includes(method)} onChange={event => customize({ paymentMethods: event.target.checked ? [...e.paymentMethods, method] : e.paymentMethods.filter(item => item !== method) })}/>{method}</label>)}</div><Field label="Custom checkout fields" hint="Separate field names with commas."><input disabled={!editing} value={c.checkoutFields} placeholder="Company, Phone number" onChange={event => configure({ checkoutFields: event.target.value })}/></Field><Field label="Thank-you page redirect"><input disabled={!editing} type="url" value={c.thankYouUrl} placeholder="https://" onChange={event => configure({ thankYouUrl: event.target.value })}/></Field></details></Card>;
}
export function OfferSettings({ product: p, products, experience: e, customize, editing }: FormProps) {
  const [editor, setEditor] = React.useState<'upsellId' | 'downsellId' | 'both' | null>(null);
  const options = products.filter(item => item.id !== p.id && (item.status === 'Active' || item.id === e.upsellId || item.id === e.downsellId));
  return <Card title="Upsell & Downsell" subtitle="Show additional offers after purchase." action={<CardSwitch disabled={!editing} label="Enable additional offers" checked={e.offersEnabled} onChange={offersEnabled => customize({ offersEnabled })}/>}>
    {(['upsellId', 'downsellId'] as const).map((key, index) => { const item = products.find(product => product.id === e[key]); return <div className="pricing-offer" key={key}><small>{index ? 'Downsell Offer' : 'Upsell Offer'}</small>{item && <div className="pricing-offer-row" onDragOver={event => { if (editing && e.offersEnabled) event.preventDefault(); }} onDrop={event => { event.preventDefault(); const source = event.dataTransfer.getData('text/gos-offer'); if (editing && e.offersEnabled && (source === 'upsellId' || source === 'downsellId') && source !== key) customize({ upsellId: e.downsellId, downsellId: e.upsellId }); }}>{item.image ? <img src={item.image} alt=""/> : <Package size={26}/>}<span><b>{item.name}</b><strong>{item.price}</strong></span><button className="cw-button small" disabled={!editing || !e.offersEnabled} onClick={() => setEditor(editor === key ? null : key)}>Edit</button><button className="pricing-drag-handle" aria-label={`Move ${index ? 'downsell' : 'upsell'} offer to ${index ? 'upsell' : 'downsell'}`} disabled={!editing || !e.offersEnabled} draggable={editing && e.offersEnabled} onDragStart={event => { event.dataTransfer.setData('text/gos-offer', key); event.dataTransfer.effectAllowed = 'move'; }} onClick={() => customize({ upsellId: e.downsellId, downsellId: e.upsellId })}><GripVertical size={13}/></button><button className="pricing-icon-button pricing-remove-offer" aria-label={`Delete ${index ? 'downsell' : 'upsell'} offer`} disabled={!editing || !e.offersEnabled} onClick={() => customize({ [key]: '' })}><Trash2 size={14}/></button></div>}{(editor === key || editor === 'both') && <Field label={index ? 'Select downsell product' : 'Select upsell product'}><CommerceSelect disabled={!editing || !e.offersEnabled} value={e[key]} onChange={value => { customize({ [key]: value }); if (editor !== 'both') setEditor(null); }} options={[{ value: '', label: 'No offer' }, ...options.map(item => ({ value: item.id, label: `${item.name} · ${item.price}` }))]}/></Field>}{!item && editor !== key && editor !== 'both' && <p className="cw-help">No offer configured</p>}</div>; })}
    <button className="cw-button cw-wide" disabled={!editing} onClick={() => { customize({ offersEnabled: true }); setEditor(editor === 'both' ? null : 'both'); }}><Plus size={13}/> Add Upsell or Downsell</button>
  </Card>;
}
export function CurrencySettings(props: FormProps) { const { config: c, experience: e, configure, customize, editing } = props; return <Card title="Currency & Region"><div className="pricing-region"><Field label="Currency"><Currency {...props}/></Field><Field label="Tax Handling"><Select disabled={!editing} value={e.taxHandling} options={['Include tax in price', 'Calculate at checkout']} onChange={taxHandling => customize({ taxHandling: taxHandling as ProductExperience['taxHandling'] })}/></Field></div><p className="cw-help">{e.taxHandling === 'Include tax in price' ? 'Displayed prices include the configured tax.' : 'Tax is added to the price at checkout.'}</p><details className="pricing-extra"><summary>Tax rate settings</summary><Field label="Tax rate (%)"><input type="number" min="0" max="100" step="0.01" disabled={!editing} value={c.taxRate} onChange={event => configure({ taxRate: Number(event.target.value) })}/></Field></details></Card>; }
