import { Plus, Trash2 } from 'lucide-react';
import type { PricingDiscount, ProductExperience } from './model';
import { accessRules } from './model';
import type { FormProps } from './TypeForms';
import { Card, Field, Select } from './primitives';
import { CardSwitch } from './PricingForms';
export function DiscountsAndCoupons({ experience: e, config: c, customize, editing }: FormProps) {
  const coupon = e.coupon;
  function updateCoupon(patch: Partial<ProductExperience['coupon']>) { customize({ coupon: { ...coupon, ...patch } }); }
  function updateDiscount(id: string, patch: Partial<PricingDiscount>) { customize({ discounts: e.discounts.map(item => item.id === id ? { ...item, ...patch } : item) }); }
  return <Card title="Discounts & Coupons" subtitle="Create special offers to boost sales." className="pricing-discounts"><div className="pricing-discount-grid">
    <Card title="Discount Code" action={<CardSwitch label="Enable discount code" checked={coupon.enabled} disabled={!editing} onChange={enabled => updateCoupon({ enabled })}/>}><div className="pricing-coupon-fields"><Field label="Code *"><input disabled={!editing || !coupon.enabled} value={coupon.code} placeholder="LAUNCH20" onChange={event => updateCoupon({ code: event.target.value })}/></Field><Field label="Discount Type"><Select disabled={!editing || !coupon.enabled} value={coupon.type} options={['Percentage', 'Fixed Amount']} onChange={type => updateCoupon({ type: type as PricingDiscount['type'] })}/></Field><Field label="Value"><span className="pricing-suffix"><input type="number" min="0.01" max={coupon.type === 'Percentage' ? 100 : undefined} step="0.01" disabled={!editing || !coupon.enabled} value={coupon.value} onChange={event => updateCoupon({ value: Number(event.target.value) })}/><small>{coupon.type === 'Percentage' ? '%' : c.currency}</small></span></Field></div><div className="pricing-coupon-limits"><label><input type="checkbox" disabled={!editing || !coupon.enabled} checked={coupon.limitUsage} onChange={event => updateCoupon({ limitUsage: event.target.checked })}/>Limit usage</label>{coupon.limitUsage && <label className="pricing-suffix"><input aria-label="Coupon usage limit" type="number" min="1" step="1" disabled={!editing || !coupon.enabled} value={coupon.usageLimit} onChange={event => updateCoupon({ usageLimit: Number(event.target.value) })}/><small>uses</small></label>}<label><input type="checkbox" disabled={!editing || !coupon.enabled} checked={coupon.geofenceOffer} onChange={event => updateCoupon({ geofenceOffer: event.target.checked })}/>Geofence Offer</label><button className="pricing-icon-button" aria-label="Clear discount code" disabled={!editing} onClick={() => updateCoupon({ code: '', enabled: false })}><Trash2 size={14}/></button></div></Card>
    <div className="tw-stack">{e.discounts.map(discount => <Card key={discount.id} title="Automatic Discount" action={<div className="pricing-discount-actions"><CardSwitch label="Enable automatic discount" checked={discount.enabled} disabled={!editing} onChange={enabled => updateDiscount(discount.id, { enabled })}/>{e.discounts.length > 1 && <button className="pricing-icon-button" disabled={!editing} aria-label="Delete automatic discount" onClick={() => customize({ discounts: e.discounts.filter(item => item.id !== discount.id) })}><Trash2 size={14}/></button>}</div>}><div className="pricing-auto-fields"><Field label="Discount Type"><Select disabled={!editing || !discount.enabled} value={discount.type} options={['Percentage', 'Fixed Amount']} onChange={type => updateDiscount(discount.id, { type: type as PricingDiscount['type'] })}/></Field><Field label="Value"><span className="pricing-suffix"><input type="number" min="0.01" step="0.01" max={discount.type === 'Percentage' ? 100 : undefined} disabled={!editing || !discount.enabled} value={discount.value} onChange={event => updateDiscount(discount.id, { value: Number(event.target.value) })}/><small>{discount.type === 'Percentage' ? '%' : c.currency}</small></span></Field><Field label="Applies To"><Select disabled={!editing || !discount.enabled} value={discount.appliesTo} options={['All pricing options', 'One-time payment', 'Payment plan', 'Subscription']} onChange={appliesTo => updateDiscount(discount.id, { appliesTo: appliesTo as PricingDiscount['appliesTo'] })}/></Field></div></Card>)}<button className="cw-button small pricing-add-discount" disabled={!editing} onClick={() => customize({ discounts: [...e.discounts, { id: crypto.randomUUID(), enabled: true, type: 'Fixed Amount', value: 10, appliesTo: 'All pricing options' }] })}><Plus size={12}/> Add Another Discount</button></div>
  </div></Card>;
}
export function ProductAccessRules({ experience: e, customize, configure, editing }: FormProps) {
  return <Card title="Product Access Rules" subtitle="When should customers get access?"><div className="pricing-access-rules">{accessRules.map(rule => <label key={rule}><input type="radio" name="product-access-rule" disabled={!editing} checked={e.accessRule === rule} onChange={() => { customize({ accessRule: rule }); configure({ delivery: rule === 'After manual approval' ? 'After approval' : 'Instant', enrollment: rule === 'After manual approval' ? 'After approval' : 'Automatic' }); }}/>{rule}</label>)}</div>{e.accessRule === 'After specific date' && <Field label="Access release date"><input type="date" disabled={!editing} value={e.accessDate} onChange={event => customize({ accessDate: event.target.value })}/></Field>}{e.accessRule === 'Drip content (scheduled release)' && <Field label="Release interval (days)" hint="Release successive modules at this interval after purchase."><input type="number" min="1" step="1" disabled={!editing} value={e.dripDays} onChange={event => customize({ dripDays: Number(event.target.value) })}/></Field>}</Card>;
}
